const root = './images/items/';
export const Perfume = [
  {
    index: 0,
    brand: '조말론',
    title: '라임 바질 앤 만다린 코롱',
    price: 139000,
    strong: 1,
    top: 2,
    second: 3,
    last: 2,
    des: '조 말론 런던의 시그니처 향. 카리브해의 산들바람에서 실려온 듯한 라임향에 톡 쏘는 바질과 향기로운 백리향이 더해져 독특한 조합을 만들어 냅니다. 현대적인 감각의 클래식한 향입니다.',
    image: './images/items/j_Basil.png',
    gender: 3,
  },
  {
    index: 1,
    brand: '조말론',
    title: '잉글리쉬 페어 앤 프리지아 코롱',
    etitle: 'English Pear & Freesia Cologne',
    price: 139000,
    strong: 1,
    top: 4,
    second: 2,
    last: 2,
    des: '가을의 정수. 화이트 프리지아 부케향에 이제 막 익은 배의 신선함을 입히고 호박, 파출리, 우디향으로 은은함을 더했습니다.',
    image: './images/items/j_EnglishPear.png',
    gender: 3,
  },
  {
    index: 2,
    brand: '조말론',
    title: '피오니 앤 블러쉬 스웨이드 코롱',
    etitle: 'Peony & Blush Suede Cologne',
    price: 139000,
    strong: 1,
    top: 4,
    second: 2,
    last: 4,
    des: '꽃의 귀족, 작약의 화려함을 담은 향. 화려하게 핀 작약에 더해진 붉은 사과의 향기로운 과즙과 순수한 자스민, 장미 그리고 카네이션, 블러쉬 스웨이드의 부드러운 관능미가 여운을 남깁니다.',
    image: `${root}j_Peony.png`,
    gender: 3,
  },
  {
    index: 3,
    brand: '조말론',
    title: '우드 세이지 앤 씨 솔트 코롱',
    etitle: 'Wood Sage & Sea Salt Cologne',
    price: 139000,
    strong: 1,
    top: 5,
    second: 4,
    last: 2,
    des: '바람부는 해안을 따라 걸으며 일상을 벗어나보세요. 하얗게 부서지는 파도, 소금기를 머금은 신선한 바다 공기. 험준한 절벽에서 느껴지는 투박한 자연의 향기와 세이지의 우디한 흙 내음이 어우러져 자유롭고 활기찬 에너지와 즐거움이 가득합니다.',
    image: `${root}j_WoodSage.png`,
    gender: 3,
  },
  {
    index: 4,
    brand: '조말론',
    title: '머르 앤 통카 코롱 인텐스',
    etitle: 'Myrrh & Tonka Cologne Intense',
    price: 189000,
    strong: 3,
    top: 4,
    second: 5,
    last: 5,
    des: '꽃의 귀족, 작약의 화려함을 담은 향. 화려하게 핀 작약에 더해진 붉은 사과의 향기로운 과즙과 순수한 자스민, 장미 그리고 카네이션, 블러쉬 스웨이드의 부드러운 관능미가 여운을 남깁니다.',
    image: '경로들어가야함(누끼 따서 파일명은 j_이름.png',
    gender: 3,
  },
  {
    index: 5,
    brand: '조말론',
    title: '허니서클 앤 다바나 코롱',
    etitle: 'Peony & Blush Suede Cologne',
    price: 139000,
    strong: 1,
    top: 4,
    second: 2,
    last: 2,
    des: '영국 전원 지대에 물결치듯이 피어 오르는 야생 허니서클은 휘감듯이 피어 오르며 어둠이 깔리면 더욱 매력적으로 빛납니다. 과일 향의 반전을 지닌 다바나의 아로마 향, 여기에 로즈 향이 가미되어 더욱 신선해 집니다. ',
    image: '경로들어가야함(누끼 따서 파일명은 j_이름.png',
    gender: 3,
  },
  {
    index: 6,
    brand: '조말론',
    title: '미모사 앤 카다멈 코롱',
    etitle: 'Peony & Blush Suede Cologne',
    price: 139000,
    strong: 1,
    top: 2,
    second: 2,
    last: 5,
    des: '골드빛 미모사의 달콤한 향이 이제 막 으깬 카다멈의 스파이시함 위로 안개처럼 피어 오릅니다. 새벽에 수확한 다마스크 로즈와 파우더리한 헬리토오프 아래 크리미한 통카와 부드러운 샌달우드 향이 물결치듯 퍼져 나가며 따뜻한 천상의 향으로 당신을 매혹시킵니다.',
    image: '경로들어가야함(누끼 따서 파일명은 j_이름.png',
    gender: 3,
  },
];
