const root = './images/items/';
export const Perfume = [
  {
    index: 0,
    brand: '조말론',
    title: '라임 바질 앤 만다린 코롱',
    etitle: 'Lime Basil & Mandarin Cologne',
    price: 139000,
    strong: 1,
    top: 2,
    second: 3,
    last: 2,
    des: '조 말론 런던의 시그니처 향. 카리브해의 산들바람에서 실려온 듯한 라임향에 톡 쏘는 바질과 향기로운 백리향이 더해져 독특한 조합을 만들어 냅니다. 현대적인 감각의 클래식한 향입니다.',
    image: `${root}j_Basil.png`,
    gender: 3,
  },
  {
    index: 1,
    brand: '조말론',
    title: '잉글리쉬 페어 앤 프리지아 코롱',
    etitle: 'English Pear & Freesia Cologne',
    price: 139000,
    strong: 1,
    top: 4,
    second: 2,
    last: 2,
    des: '가을의 정수. 화이트 프리지아 부케향에 이제 막 익은 배의 신선함을 입히고 호박, 파출리, 우디향으로 은은함을 더했습니다.',
    image: `${root}j_EnglishPear.png`,
    gender: 3,
  },
  {
    index: 2,
    brand: '조말론',
    title: '피오니 앤 블러쉬 스웨이드 코롱',
    etitle: 'Peony & Blush Suede Cologne',
    price: 139000,
    strong: 1,
    top: 4,
    second: 2,
    last: 4,
    des: '꽃의 귀족, 작약의 화려함을 담은 향. 화려하게 핀 작약에 더해진 붉은 사과의 향기로운 과즙과 순수한 자스민, 장미 그리고 카네이션, 블러쉬 스웨이드의 부드러운 관능미가 여운을 남깁니다.',
    image: `${root}j_Peony.png`,
    gender: 3,
  },
  {
    index: 3,
    brand: '조말론',
    title: '우드 세이지 앤 씨 솔트 코롱',
    etitle: 'Wood Sage & Sea Salt Cologne',
    price: 139000,
    strong: 1,
    top: 5,
    second: 4,
    last: 2,
    des: '바람부는 해안을 따라 걸으며 일상을 벗어나보세요. 하얗게 부서지는 파도, 소금기를 머금은 신선한 바다 공기. 험준한 절벽에서 느껴지는 투박한 자연의 향기와 세이지의 우디한 흙 내음이 어우러져 자유롭고 활기찬 에너지와 즐거움이 가득합니다.',
    image: `${root}j_WoodSage.png`,
    gender: 3,
  },
  {
    index: 4,
    brand: '조말론',
    title: '머르 앤 통카 코롱 인텐스',
    etitle: 'Myrrh & Tonka Cologne Intense',
    price: 189000,
    strong: 2,
    top: 4,
    second: 5,
    last: 5,
    des: '꽃의 귀족, 작약의 화려함을 담은 향. 화려하게 핀 작약에 더해진 붉은 사과의 향기로운 과즙과 순수한 자스민, 장미 그리고 카네이션, 블러쉬 스웨이드의 부드러운 관능미가 여운을 남깁니다.',
    image: `${root}j_Myrrt.png`,
    gender: 3,
  },
  {
    index: 5,
    brand: '조말론',
    title: '허니서클 앤 다바나 코롱',
    etitle: 'Honeysuckle & Davana Cologne',
    price: 139000,
    strong: 1,
    top: 4,
    second: 2,
    last: 2,
    des: '영국 전원 지대에 물결치듯이 피어 오르는 야생 허니서클은 휘감듯이 피어 오르며 어둠이 깔리면 더욱 매력적으로 빛납니다. 과일 향의 반전을 지닌 다바나의 아로마 향, 여기에 로즈 향이 가미되어 더욱 신선해 집니다. ',
    image: `${root}j_Honeysuckle.png`,
    gender: 3,
  },
  {
    index: 6,
    brand: '조말론',
    title: '미모사 앤 카다멈 코롱',
    etitle: 'Mimosa & Cardamom Cologne',
    price: 139000,
    strong: 1,
    top: 2,
    second: 2,
    last: 5,
    des: '골드빛 미모사의 달콤한 향이 이제 막 으깬 카다멈의 스파이시함 위로 안개처럼 피어 오릅니다. 새벽에 수확한 다마스크 로즈와 파우더리한 헬리토오프 아래 크리미한 통카와 부드러운 샌달우드 향이 물결치듯 퍼져 나가며 따뜻한 천상의 향으로 당신을 매혹시킵니다.',
    image: `${root}j_Mimosa.png`,
    gender: 3,
  },
  {
    index: 7,
    brand: '조말론',
    title: '레드 로즈 코롱',
    etitle: 'Red Roses Cologne',
    price: 139000,
    strong: 1,
    top: 2,
    second: 2,
    last: 5,
    des: '현대적인 로맨스의 상징. 세상에서 가장 아름다운 일곱가지 장미가 조합된 관능적인 향입니다. 으깬 바이올렛 잎과 약간의 레몬이 조합되어 신선한 부케향을 발산합니다. 놀라울 정도로 투명하고 순수한 향을 선사합니다.',
    image: `${root}j_Redroses.png`,
    gender: 3,
  },
  {
    index: 8,
    brand: '조말론',
    title: '와일드 블루벨 코롱',
    etitle: 'Wild Bluebell Cologne',
    price: 139000,
    strong: 1,
    top: 1,
    second: 1,
    last: 3,
    des: '숲 속 깊은 곳에서 빛나고 있는 사파이어. 이슬 맺힌 블루벨의 은은하고 달콤한 향에 릴리와 들장미 향의 조화가 최면을 걸 듯 마음을 사로잡습니다.',
    image: `${root}j_Wildblubellpng`,
    gender: 3,
  },
  {
    index: 9,
    brand: '조말론',
    title: '스칼렛 포피 코롱 인텐스',
    etitle: 'Scarlet Poppy Cologne Intense',
    price: 191000,
    strong: 2,
    top: 4,
    second: 2,
    last: 5,
    des: ' 아시아 야생의 초원에서 자라난 화려한 ‘꽃양귀비’ (Great Scarlet Poppy)에서 영감을 받아 탄생한 향 입니다. 부드러운 아이리스 꽃 향, 보리, 그리고 통카 빈 노트가 달콤한 퇴폐미를 강조하고, 과즙이 가득한 무화과 어코드가 향을 한층 풍부하게 만들어줍니다.',
    image: `${root}j_Scalepoppy.png`,
    gender: 3,
  },
  {
    index: 10,
    brand: '샤넬',
    title: '샹스 오 후레쉬',
    etitle: 'CHANCE EAU FRAÎCHE',
    price: 137000,
    strong: 3,
    top: 2,
    second: 2,
    last: 2,
    des: '샤넬의 코’로 불리우는 자크 뽈쥬는 기대하지 못했던 환희의 샹스를 더욱 대담하며 환상으로 가득 찬 향조로 재해석하였습니다.기대하지 못했던 환희의 플로랄 향조는 톡 쏘는듯 상큼하고 생동감 있는 플로랄 향조가 되었습니다.',
    image: `${root}c_Fresh.png`,
    gender: 1,
  },
  {
    index: 11,
    brand: '샤넬',
    title: '알뤼르 오드 빠르펭',
    etitle: 'ALLURE SENSUELLE',
    price: 168000,
    strong: 4,
    top: 2,
    second: 2,
    last: 2,
    des: '마드모아젤 샤넬이 정의한 고결한 품격. 있는 그대로의 카리스마. 모든 여성을 위해 여섯 가지의 향이 서로 다르게 표현되는 플로랄-프레쉬-엠버리 향수. 여성이 지닌 각자의 고유한 매력을 강조합니다.',
    image: `${root}c_Allure`,
    gender: 3,
  },
  {
    index: 12,
    brand: '샤넬',
    title: '샹스 오 비브 오드 뚜왈렛',
    etitle: 'CHANCE EAU VIVE',
    price: 137000,
    strong: 3,
    top: 2,
    second: 2,
    last: 1,
    des: '자몽과 블러드 오렌지의 상큼한 향이 더해진 생기 넘치는 플로랄 계열의 향수. 탑 노트의 즐거운 향을 경험해 보세요. 뒤이은 쟈스민 향은 섬세하게 여성성을 드러내고 맑고 투명한 시더-아이리스 향으로 은은하고 우아한 마무리를 선사합니다',
    image: `${root}c_Vive`,
    gender: 1,
  },
  {
    index: 13,
    brand: '샤넬',
    title: '샹스 오 땅드르',
    etitle: 'CHANCE EAU TENDRE',
    price: 137000,
    strong: 3,
    top: 2,
    second: 2,
    last: 3,
    des:'순수한 향기의 시, 프루티-플로랄 향, 부드러움의 달콤한 물결,자몽과 모과 향이 쟈스민과 어우러져 화이트 머스크의 둥글고 여성적인 노트에 의해 따스함이 더해집니다.이 새롭고 거부할 수 없는 매혹적인 행운의 향은 행복을 믿고 기회를 놓치지 않는 낙천적인 여성의 향기입니다.',
    image: `${root}c_Tendre`,
    gender: 1,
  },
  {
    index: 14,
    brand: '샤넬',
    title: '코코 마드모아젤',
    etitle: 'COCO MADEMOISELLE',
    price: 168000,
    strong: 4,
    top: 2,
    second: 2,
    last: 5,
    des: '오리엔탈-훌로랄. 따뜻하고도 관능적인 향. 후레쉬하고 관능적이며 섹시하고 세련된 향이 완벽한 모던함을 표현합니다',
    image: `${root}c_Coco`,
    gender: 1,
  },
  {
    index: 15,
    brand: '샤넬',
    title: '샤넬 No.5',
    etitle: 'No.5',
    price: 168000,
    strong: 4,
    top: 2,
    second: 2,
    last: 3,
    des: 'N°5, 여성미의 정수. 알데하이드 플로랄 부케 향수는 미니멀한 디자인이 돋보이는 아이코닉 보틀로 선보입니다. 시간을 초월한 유서 깊은 샤넬의 아이콘.',
    image: `${root}c_no`,
    gender: 1,
  },
  {
    index: 16,
    brand: '샤넬',
    title: '알뤼르 옴므 스포츠',
    etitle: 'ALLURE HOMME SPORT',
    price: 110000,
    strong: 3,
    top: 2,
    second: 4,
    last: 2,
    des: '신선한 우디 향수.수분감으로 가득한 신선하고 감각적인 노트가 역동성을 분출하는 남성성을 표현합니다.',
    image: `${root}c_Sport`,
    gender: 2,
  },
  {
    index: 17,
    brand: '샤넬',
    title: '가브리엘 샤넬',
    etitle: 'GABRIELLE CHANEL',
    price: 168000,
    strong: 4,
    top: 2,
    second: 5,
    last: 3,
    des: '가브리엘 샤넬 오 드 빠르펭은 빛을 머금은 향수입니다. 이국적이고 강렬한 쟈스민, 생동감 넘치는 과일 향이 매력적인 일랑일랑, 신선하고 반짝이는 오렌지 블라썸, 그리고 부드럽고 섬세한 그라스 튜베로즈를 포함한 4가지의 꽃향기가 어우러져 완성된 순수한 플로랄 향을 선사합니다.',
    image: `${root}c_Gabrielle`,
    gender: 1,
  },
  {
    index: 18,
    brand: '샤넬',
    title: '블루 드 샤넬',
    etitle: 'BLEU DE CHANEL',
    price: 127000,
    strong: 4,
    top: 4,
    second: 5,
    last: 2,
    des: '블루 드 샤넬 오 드 빠르펭은 앰버리한 시더와 베네수엘라 통카빈이 뉴칼레도니아 샌달우드의 우아하고 깊이있는 향과 조화를 이루어 따뜻하고 관능적인 느낌을 자아내는 우디 아로마틱 향수입니다.',
    image: `${root}c_Blue`,
    gender: 2,
  },
  {
    index: ,
    brand: '',
    title: '',
    etitle: '',
    price: ,
    strong: ,
    top: ,
    second: ,
    last: ,
    des: '',
    image: `${root}`,
    gender: ,
  },
  {
    index: ,
    brand: '',
    title: '',
    etitle: '',
    price: ,
    strong: ,
    top: ,
    second: ,
    last: ,
    des: '',
    image: `${root}`,
    gender: ,
  },

];
