const root = './images/items/';
export const Perfume = [
  {
    index: 0,
    brand: '조말론',
    title: '라임 바질 앤 만다린 코롱',
    etitle: 'Lime Basil & Mandarin Cologne',
    price: 139000,
    strong: 1,
    top: 2,
    second: 3,
    last: 2,
    des: '조 말론 런던의 시그니처 향. 카리브해의 산들바람에서 실려온 듯한 라임향에 톡 쏘는 바질과 향기로운 백리향이 더해져 독특한 조합을 만들어 냅니다. 현대적인 감각의 클래식한 향입니다.',
    image: `${root}j_Basil.png`,
    gender: 3,
  },
  {
    index: 1,
    brand: '조말론',
    title: '잉글리쉬 페어 앤 프리지아 코롱',
    etitle: 'English Pear & Freesia Cologne',
    price: 139000,
    strong: 1,
    top: 4,
    second: 2,
    last: 2,
    des: '가을의 정수. 화이트 프리지아 부케향에 이제 막 익은 배의 신선함을 입히고 호박, 파출리, 우디향으로 은은함을 더했습니다.',
    image: `${root}j_EnglishPear.png`,
    gender: 3,
  },
  {
    index: 2,
    brand: '조말론',
    title: '피오니 앤 블러쉬 스웨이드 코롱',
    etitle: 'Peony & Blush Suede Cologne',
    price: 139000,
    strong: 1,
    top: 4,
    second: 2,
    last: 4,
    des: '꽃의 귀족, 작약의 화려함을 담은 향. 화려하게 핀 작약에 더해진 붉은 사과의 향기로운 과즙과 순수한 자스민, 장미 그리고 카네이션, 블러쉬 스웨이드의 부드러운 관능미가 여운을 남깁니다.',
    image: `${root}j_Peony.png`,
    gender: 3,
  },
  {
    index: 3,
    brand: '조말론',
    title: '우드 세이지 앤 씨 솔트 코롱',
    etitle: 'Wood Sage & Sea Salt Cologne',
    price: 139000,
    strong: 1,
    top: 5,
    second: 4,
    last: 2,
    des: '바람부는 해안을 따라 걸으며 일상을 벗어나보세요. 하얗게 부서지는 파도, 소금기를 머금은 신선한 바다 공기. 험준한 절벽에서 느껴지는 투박한 자연의 향기와 세이지의 우디한 흙 내음이 어우러져 자유롭고 활기찬 에너지와 즐거움이 가득합니다.',
    image: `${root}j_WoodSage.png`,
    gender: 3,
  },
  {
    index: 4,
    brand: '조말론',
    title: '머르 앤 통카 코롱 인텐스',
    etitle: 'Myrrh & Tonka Cologne Intense',
    price: 189000,
    strong: 2,
    top: 4,
    second: 5,
    last: 5,
    des: '꽃의 귀족, 작약의 화려함을 담은 향. 화려하게 핀 작약에 더해진 붉은 사과의 향기로운 과즙과 순수한 자스민, 장미 그리고 카네이션, 블러쉬 스웨이드의 부드러운 관능미가 여운을 남깁니다.',
    image: `${root}j_Myrrt.png`,
    gender: 3,
  },
  {
    index: 5,
    brand: '조말론',
    title: '허니서클 앤 다바나 코롱',
    etitle: 'Honeysuckle & Davana Cologne',
    price: 139000,
    strong: 1,
    top: 4,
    second: 2,
    last: 2,
    des: '영국 전원 지대에 물결치듯이 피어 오르는 야생 허니서클은 휘감듯이 피어 오르며 어둠이 깔리면 더욱 매력적으로 빛납니다. 과일 향의 반전을 지닌 다바나의 아로마 향, 여기에 로즈 향이 가미되어 더욱 신선해 집니다. ',
    image: `${root}j_Honeysuckle.png`,
    gender: 3,
  },
  {
    index: 6,
    brand: '조말론',
    title: '미모사 앤 카다멈 코롱',
    etitle: 'Mimosa & Cardamom Cologne',
    price: 139000,
    strong: 1,
    top: 2,
    second: 2,
    last: 5,
    des: '골드빛 미모사의 달콤한 향이 이제 막 으깬 카다멈의 스파이시함 위로 안개처럼 피어 오릅니다. 새벽에 수확한 다마스크 로즈와 파우더리한 헬리토오프 아래 크리미한 통카와 부드러운 샌달우드 향이 물결치듯 퍼져 나가며 따뜻한 천상의 향으로 당신을 매혹시킵니다.',
    image: `${root}j_Mimosa.png`,
    gender: 3,
  },
  {
    index: 7,
    brand: '조말론',
    title: '레드 로즈 코롱',
    etitle: 'Red Roses Cologne',
    price: 139000,
    strong: 1,
    top: 2,
    second: 2,
    last: 5,
    des: '현대적인 로맨스의 상징. 세상에서 가장 아름다운 일곱가지 장미가 조합된 관능적인 향입니다. 으깬 바이올렛 잎과 약간의 레몬이 조합되어 신선한 부케향을 발산합니다. 놀라울 정도로 투명하고 순수한 향을 선사합니다.',
    image: `${root}j_Redroses.png`,
    gender: 3,
  },
  {
    index: 8,
    brand: '조말론',
    title: '와일드 블루벨 코롱',
    etitle: 'Wild Bluebell Cologne',
    price: 139000,
    strong: 1,
    top: 1,
    second: 1,
    last: 3,
    des: '숲 속 깊은 곳에서 빛나고 있는 사파이어. 이슬 맺힌 블루벨의 은은하고 달콤한 향에 릴리와 들장미 향의 조화가 최면을 걸 듯 마음을 사로잡습니다.',
    image: `${root}j_Wildblubell.png`,
    gender: 3,
  },
  {
    index: 9,
    brand: '조말론',
    title: '스칼렛 포피 코롱 인텐스',
    etitle: 'Scarlet Poppy Cologne Intense',
    price: 191000,
    strong: 2,
    top: 4,
    second: 2,
    last: 5,
    des: ' 아시아 야생의 초원에서 자라난 화려한 ‘꽃양귀비’ (Great Scarlet Poppy)에서 영감을 받아 탄생한 향 입니다. 부드러운 아이리스 꽃 향, 보리, 그리고 통카 빈 노트가 달콤한 퇴폐미를 강조하고, 과즙이 가득한 무화과 어코드가 향을 한층 풍부하게 만들어줍니다.',
    image: `${root}j_Scalepoppy.png`,
    gender: 3,
  },
  {
    index: 10,
    brand: '샤넬',
    title: '샹스 오 후레쉬',
    etitle: 'CHANCE EAU FRAÎCHE',
    price: 137000,
    strong: 3,
    top: 2,
    second: 2,
    last: 2,
    des: '샤넬의 코’로 불리우는 자크 뽈쥬는 기대하지 못했던 환희의 샹스를 더욱 대담하며 환상으로 가득 찬 향조로 재해석하였습니다.기대하지 못했던 환희의 플로랄 향조는 톡 쏘는듯 상큼하고 생동감 있는 플로랄 향조가 되었습니다.',
    image: `${root}c_Fresh.png`,
    gender: 1,
  },
  {
    index: 11,
    brand: '샤넬',
    title: '알뤼르 오드 빠르펭',
    etitle: 'ALLURE SENSUELLE',
    price: 168000,
    strong: 4,
    top: 2,
    second: 2,
    last: 2,
    des: '마드모아젤 샤넬이 정의한 고결한 품격. 있는 그대로의 카리스마. 모든 여성을 위해 여섯 가지의 향이 서로 다르게 표현되는 플로랄-프레쉬-엠버리 향수. 여성이 지닌 각자의 고유한 매력을 강조합니다.',
    image: `${root}c_Allure.png`,
    gender: 3,
  },
  {
    index: 12,
    brand: '샤넬',
    title: '샹스 오 비브 오드 뚜왈렛',
    etitle: 'CHANCE EAU VIVE',
    price: 137000,
    strong: 3,
    top: 2,
    second: 2,
    last: 1,
    des: '자몽과 블러드 오렌지의 상큼한 향이 더해진 생기 넘치는 플로랄 계열의 향수. 탑 노트의 즐거운 향을 경험해 보세요. 뒤이은 쟈스민 향은 섬세하게 여성성을 드러내고 맑고 투명한 시더-아이리스 향으로 은은하고 우아한 마무리를 선사합니다',
    image: `${root}c_Vive.png`,
    gender: 1,
  },
  {
    index: 13,
    brand: '샤넬',
    title: '샹스 오 땅드르',
    etitle: 'CHANCE EAU TENDRE',
    price: 137000,
    strong: 3,
    top: 2,
    second: 2,
    last: 3,
    des: '순수한 향기의 시, 프루티-플로랄 향, 부드러움의 달콤한 물결,자몽과 모과 향이 쟈스민과 어우러져 화이트 머스크의 둥글고 여성적인 노트에 의해 따스함이 더해집니다.이 새롭고 거부할 수 없는 매혹적인 행운의 향은 행복을 믿고 기회를 놓치지 않는 낙천적인 여성의 향기입니다.',
    image: `${root}c_Tendre.png`,
    gender: 1,
  },
  {
    index: 14,
    brand: '샤넬',
    title: '코코 마드모아젤',
    etitle: 'COCO MADEMOISELLE',
    price: 168000,
    strong: 4,
    top: 2,
    second: 2,
    last: 5,
    des: '오리엔탈-훌로랄. 따뜻하고도 관능적인 향. 후레쉬하고 관능적이며 섹시하고 세련된 향이 완벽한 모던함을 표현합니다',
    image: `${root}c_Coco.png`,
    gender: 1,
  },
  {
    index: 15,
    brand: '샤넬',
    title: '샤넬 No.5',
    etitle: 'No.5',
    price: 168000,
    strong: 4,
    top: 2,
    second: 2,
    last: 3,
    des: 'N°5, 여성미의 정수. 알데하이드 플로랄 부케 향수는 미니멀한 디자인이 돋보이는 아이코닉 보틀로 선보입니다. 시간을 초월한 유서 깊은 샤넬의 아이콘.',
    image: `${root}c_no5.png`,
    gender: 1,
  },
  {
    index: 16,
    brand: '샤넬',
    title: '알뤼르 옴므 스포츠',
    etitle: 'ALLURE HOMME SPORT',
    price: 110000,
    strong: 3,
    top: 2,
    second: 4,
    last: 2,
    des: '신선한 우디 향수.수분감으로 가득한 신선하고 감각적인 노트가 역동성을 분출하는 남성성을 표현합니다.',
    image: `${root}c_Sport.png`,
    gender: 2,
  },
  {
    index: 17,
    brand: '샤넬',
    title: '가브리엘 샤넬',
    etitle: 'GABRIELLE CHANEL',
    price: 168000,
    strong: 4,
    top: 2,
    second: 5,
    last: 3,
    des: '가브리엘 샤넬 오 드 빠르펭은 빛을 머금은 향수입니다. 이국적이고 강렬한 쟈스민, 생동감 넘치는 과일 향이 매력적인 일랑일랑, 신선하고 반짝이는 오렌지 블라썸, 그리고 부드럽고 섬세한 그라스 튜베로즈를 포함한 4가지의 꽃향기가 어우러져 완성된 순수한 플로랄 향을 선사합니다.',
    image: `${root}c_Gabrielle.png`,
    gender: 1,
  },
  {
    index: 18,
    brand: '샤넬',
    title: '블루 드 샤넬',
    etitle: 'BLEU DE CHANEL',
    price: 127000,
    strong: 4,
    top: 4,
    second: 5,
    last: 2,
    des: '블루 드 샤넬 오 드 빠르펭은 앰버리한 시더와 베네수엘라 통카빈이 뉴칼레도니아 샌달우드의 우아하고 깊이있는 향과 조화를 이루어 따뜻하고 관능적인 느낌을 자아내는 우디 아로마틱 향수입니다.',
    image: `${root}c_Blue.png`,
    gender: 2,
  },
  {
    index: 19,
    brand: '딥디크',
    title: '도 손 오드 퍼퓸(75ml)',
    etitle: 'DO SON EAU DE PARFUM',
    price: 235000,
    strong: 4,
    top: 4,
    second: 1,
    last: 2,
    des: '큰 항구도시 하이퐁의 습한 열기로부터 멀리 떨어져 있는 도손의 공기는 좀 더 시원했습니다. 은은한 향신료 향이 어우러진 황홀한 튜베로즈 향기가 해풍에 실려갑니다. ',
    image: `${root}d_Doson.png`,
    gender: 3,
  },
  {
    index: 20,
    brand: '딥디크',
    title: '베티베이리오 오드 뚜왈렛',
    etitle: 'VETYVERIO EDT',
    price: 143000,
    strong: 3,
    top: 2,
    second: 2,
    last: 5,
    des: '플로리다산 자몽과 터키산 장미의 향기로운 조화를 이루는 향수, 우디향의 향수로 시원하고 풀향이 나는 것이 특징! ',
    image: `${root}d_Vetyverio.png`,
    gender: 3,
  },
  {
    index: 21,
    brand: '딥디크',
    title: '플레드 드뽀 오드 퍼퓸(75ml)',
    etitle: 'fleur de peau',
    price: 235000,
    strong: 4,
    top: 3,
    second: 5,
    last: 3,
    des: '피부의 꽃이라는 뜻으로 머스크와 아이리스가 어우러진 부드럽고 파우더리한 향수 첫향은 강하다는 의견이 많지만 잔향이 좋아 인기가 많다',
    image: `${root}d_Fleur.png`,
    gender: 3,
  },
  {
    index: 22,
    brand: '딥디크',
    title: '필로시코스 오드 뚜왈렛(75ml)',
    etitle: 'Philosykos',
    price: 235000,
    strong: 3,
    top: 4,
    second: 4,
    last: 2,
    des: '그린 우디 플로랄 계열, 내추럴한 무화과 향기 무화과 열매뿐만 아니라 나무 향과 따스한 흙향도 함께 느껴지는 향수, 산뜻하고 달달한 것이 특징',
    image: `${root}d_Philosykos.png`,
    gender: 3,
  },
  {
    index: 23,
    brand: '딥디크',
    title: '탐 다오 오드 퍼퓸',
    etitle: 'Tam dao',
    price: 143000,
    strong: 4,
    top: 2,
    second: 3,
    last: 2,
    des: '복잡했던 마을을 한꺼번에 달래줄 법한, 신선한 공기 가득한 숲속의 사찰 마루에서 날법한 나무향입니다. 차분한 느낌이 특징',
    image: `${root}d_Tam.png`,
    gender: 3,
  },
  {
    index: 24,
    brand: '딥디크',
    title: '롬보르 단 로 오드 뚜왈렛(75ml)',
    etitle: `L'OMBRE DANS`,
    price: 235000,
    strong: 3,
    top: 3,
    second: 4,
    last: 5,
    des: '시원한 향을 주는 블랙 커런트 잎과 헤드 노트인 불가리안 로즈가 완벽한 조화를 이뤄 럭셔리 하면서도 세련된 향을 선사한다.',
    image: `${root}d_L.png`,
    gender: 3,
  },
  {
    index: 25,
    brand: '딥디크',
    title: '오 데 썽 오드 뚜왈렛',
    etitle: 'EAU DES SENS',
    price: 143000,
    strong: 3,
    top: 2,
    second: 5,
    last: 2,
    des: '오렌지 나무 한그루를 감각적으로 담아내 과육의 풍미와 달콤함, 초록색 줄기의 싱그러움이 모두 느껴지는 향수, 오렌지향과 우드, 머스크향이 조화된 향수',
    image: `${root}d_Des.png`,
    gender: 3,
  },
  {
    index: 26,
    brand: '딥디크',
    title: '오 로즈 오드 뚜왈렛',
    etitle: 'EAU ROSE',
    price: 143000,
    strong: 3,
    top: 3,
    second: 2,
    last: 3,
    des: '장미 에센스 중 가장 귀한 센티폴리아 장미가 하트 노트로 사용되어 매혹적인 플로럴 향이 공기의 숨결을 따라 은은하게 퍼져나가는 향수',
    image: `${root}d_Rose.png`,
    gender: 3,
  },
  {
    index: 27,
    brand: '구찌',
    title: '[구찌 길티] 오 드 퍼퓸 인텐스 뿌르 팜므',
    etitle: 'Gucci Guilty Eau de Parfum Intense Pour Femme',
    price: 160000,
    strong: 4,
    top: 3,
    second: 2,
    last: 3,
    des: '사회의 규범과 관념에 얽매이지 않는 사랑을 선언하고자 하는 이들을 위한 향수에 강렬함을 한층 더합니다. 마음이 서로 잘 맞는 연인을 연결하는 상징으로 디자인된 구찌 길티 오 드 퍼퓸 인텐스 뿌르 팜므는 구찌 길티 뿌르 팜므의 핵심 시그니처 향을 재해석한 앰버 플로라 우디 향이 특징적입니다.',
    image: `${root}g_Guiltypourfemme.png`,
    gender: 1,
  },
  {
    index: 28,
    brand: '구찌',
    title: '[알케미스트 가든] 오 드 퍼퓸 A Gloaming Night(100ml) ',
    etitle: 'The Alchemist’s Garden A Gloaming Night',
    price: 440000,
    strong: 4,
    top: 4,
    second: 2,
    last: 1,
    des: '아름다운 일몰의 컬러에서 영감을 받은 향은 핑크, 퍼플, 피치, 레드 컬러의 하늘이 수평선 위로 으스름을 만들어내듯이 서로 어우러져 특별한 아로마를 완성합니다. 알레산드로 미켈레의 창의적인 디렉션을 통해 마스터 조향사인 알베르토 모리야스(Alberto Morillas)가 블렌딩하여 선보이는 커스텀 가능한 이 상품은 오 드 퍼퓸, 퍼퓸 오일, 퍼퓸 워터로 만나보실 수 있습니다.',
    image: `${root}g_Gloamingnight.png`,
    gender: 3,
  },
  {
    index: 29,
    brand: '구찌',
    title: '[알케미스트 가든] 오 드 퍼퓸 1921(100ml) ',
    etitle: 'The Alchemist’s Garden 1921',
    price: 440000,
    strong: 4,
    top: 4,
    second: 4,
    last: 2,
    des: 'Gucci 100주년을 기념하여 1921이라는 이름의 새로운 스페셜 향수가 알케미스트 가든 럭셔리 컬렉션에 추가되었습니다. 상징적인 네롤리 플라워를 중심으로 구성된 향수는 하우스의 또 다른 헤리티지인 구찌가 창립된 피렌체에서 재배한 시트론 레몬향이 돋보입니다.',
    image: `${root}g_1921.png`,
    gender: 3,
  },
  {
    index: 30,
    brand: '구찌',
    title:
      '[알케미스트 가든]오 드 퍼퓸 A Chant for the Nymph,프랑지파니(100ml)',
    etitle: 'A Chant for the Nymph, Frangipani',
    price: 440000,
    strong: 4,
    top: 1,
    second: 2,
    last: 5,
    des: '꽃으로 가득한 열대우림에서 영감을 얻은 프랑지파니 향수입니다. 따뜻한 밤에 피어나는 상쾌하고 오래 지속되는 향으로 불멸성을 상징하는 프랑지파니 꽃이 향수를 정의하며, 한여름 밤의 꿈에 등장하는 오래 전에 잊혀진 신화적인 존재, 님프의 이야기를 떠올리게 합니다.',
    image: `${root}g_Nymph.png`,
    gender: 3,
  },
  {
    index: 31,
    brand: '구찌',
    title: '[구찌 블룸] 오 드 퍼퓸 암브로시아 디 피오리',
    etitle: 'Gucci Bloom Ambrosia di Fiori',
    price: 160000,
    strong: 4,
    top: 3,
    second: 2,
    last: 3,
    des: '고대 시대의 연회를 연상시키는 암브로시아는 그리스 신들의 음료로, 마시는 사람에게 영생을 준다고 전해져 내려옵니다. 이러한 전설이 담겨있는 이름과 신비로운 마법에서 유래된 향수에 생기 있는 향을 더하여 탄생하였습니다. 오리지널 구찌 블룸 오드 퍼퓸의 세가지 조합인 자스민 봉오리, 튜베로즈, 그리고 랑군 덩굴에 고대 그리스 로마 사람들에게 최고로 여겨 졌던 아이리스 뿌리에서 추출 한 벨베티 오리스와 가장 풍성한 향을 뿜어내는 장미 품종인 다마스크 로즈 향을 더했습니다. ',
    image: `${root}g_Ambrosia.png`,
    gender: 1,
  },
  {
    index: 32,
    brand: '구찌',
    title: '[구찌 블룸] 오 드 퍼퓸 프로푸모 디 피오리',
    etitle: 'Gucci Bloom Profumo di Fiori',
    price: 160000,
    strong: 4,
    top: 3,
    second: 2,
    last: 3,
    des: '클래식한 구찌 블룸을 재해석한 프로모프 디 피오리는 아라비아 재스민과 튜베로즈를 블렌딩해서 중독성 있는 향기가 은은히 퍼져나갑니다.',
    image: `${root}g_Profumo.png`,
    gender: 1,
  },
  {
    index: 33,
    brand: '구찌',
    title: '[구찌 길티]오 드 퍼퓸 뿌르 옴므',
    etitle: 'Gucci Guilty Parfum Pour Homme',
    price: 119000,
    strong: 4,
    top: 3,
    second: 2,
    last: 2,
    des: '마음이 서로 잘 맞는 연인을 연결하는 상징으로 디자인된 구찌 길티 퍼퓸 뿌르 옴므는 구찌 길티 뿌르 옴므의 시그니처 향을 더욱 강렬하게 표현한 우디 아로마틱 앰버 향이 특징적입니다.',
    image: `${root}g_Pourhomme.png`,
    gender: 2,
  },
  {
    index: 34,
    brand: '구찌',
    title: '오 드 퍼퓸 구찌 메모아 뒨 오더(100ml)',
    etitle: 'Gucci Mémoire d`une Odeur',
    price: 201000,
    strong: 4,
    top: 3,
    second: 6,
    last: 2,
    des: '16세기와 17세기 로마의 테라스가 있는 정원에서 자란 로만 카모마일의 싱그러운 아로마 향과 밤이면 더욱 강한 향을 자아내는 인디언 코럴 자스민의 향을 블렌딩하였습니다. 머스크 향이 향수에 깊이를 더하고, 시더우드와 샌들우드가 강렬함을 더합니다.',
    image: `${root}g_Memoire.png`,
    gender: 2,
  },
  {
    index: 35,
    brand: '구찌',
    title: '[구찌 길티] 오 드 뚜왈렛 뿌르 옴므',
    etitle: 'Gucci Guilty Eau de toilette Pour Homme',
    price: 103000,
    strong: 3,
    top: 2,
    second: 4,
    last: 2,
    des: '미스테리하고 관능적이며 은밀한 매력을 현대적인 감성으로 풀어낸 파촐리의 베이스 노트. 강렬한 남성성을 느낄 수 있는 시더 우드의 드라이 다운 노트로 구성되어 있습니다. 구찌 길티 뿌르 옴므의 청동 도금된 향수 병과 뚜껑은 웜톤 퍼플 그레이 색상의 향수와 조화를 이룹니다.',
    image: `${root}g_Guiltytoilette.png`,
    gender: 2,
  },
  {
    index: 36,
    brand: '불가리',
    title: '오 드 뚜왈렛 옴니아 핑크 사파이어(40ml)',
    etitle: 'Eau de toilette Omnia Pink Sapphire',
    price: 113000,
    strong: 3,
    top: 4,
    second: 1,
    last: 3,
    des: '플로럴 계열의 옴니아 핑크 사파이어는 향수에 영감이 되어준 젬스톤의 컬러처럼 눈부신 햇살이 내리쬐는 어느 화창한 날의 축제를 떠올리게 하는, 열정적이면서도 독특한 향을 선사합니다. 본질에 맞게 정확히 어우러진 성분들이 강렬한 아름다움과 감각적인 풍부함이 고스란히 느껴지는 자연의 힘을 구현합니다.',
    image: `${root}b_Omniapink.png`,
    gender: 1,
  },
  {
    index: 37,
    brand: '불가리',
    title: '로즈 골데아 오 드 퍼퓸',
    etitle: 'Rose Goldea Bvlgari',
    price: 146000,
    strong: 4,
    top: 2,
    second: 2,
    last: 2,
    des: '불가리는 화려한 장미와 섬세한 머스크로 여성스러운 감성을 자아내는 로즈 골데아를 선보입니다. 불가리의 상징과도 같은 세르펜티 컬렉션에서 영감을 받은 로즈 골데아는 거부할 수 없는 열정적인 사랑을 상징하는 대담한 매력의 주얼리처럼 화려하게 피어납니다.',
    image: `${root}b_Rose.png`,
    gender: 1,
  },
  {
    index: 38,
    brand: '불가리',
    title: '로즈 골데아 블라썸 딜라이트 오 드 퍼퓸',
    etitle: 'ROSE GOLDEA BLOSSOM DELIGHT',
    price: 146000,
    strong: 4,
    top: 3,
    second: 2,
    last: 3,
    des: '부드러운 꽃잎에서부터 강렬한 우아함을 품은 하트 노트에 이르기까지, 로즈 골데아 블러썸 딜라이트 오 드 퍼퓸은 계속해서 성장을 거듭하는 로즈버드의 생기를 재현하며 더욱더 화려하게 피어나는 장미 특유의 매력을 온전히 담아냅니다.',
    image: `${root}b_Goldea.png`,
    gender: 1,
  },
  {
    index: 39,
    brand: '불가리',
    title: '불가리 뿌르 옴므 익스트림 오 드 뚜왈렛',
    etitle: 'BVLGARI POUR HOMME',
    price: 89000,
    strong: 3,
    top: 2,
    second: 3,
    last: 5,
    des: '불가리 뿌르 옴므 익스트림은 불가리 뿌르 옴므를 재해석한 신선하고 생동감 넘치는 향수로, 시간을 초월한 세련된 남성의 품격을 표현하는 전형적인 표상입니다.',
    image: `${root}b_Homme.png`,
    gender: 2,
  },
  {
    index: 40,
    brand: '불가리',
    title: '맨 우드 에센스 오 드 퍼퓸(60ml)',
    etitle: 'Man Wood Essence EDP',
    price: 100000,
    strong: 4,
    top: 2,
    second: 4,
    last: 2,
    des: '시더, 사이프러스, 베티버와 같은 최고급 에센스 그리고 따뜻한 태양 빛을 닮은 벤조인 레진 노트가 아름답게 공명하는 네오 우디 계열의 향수',
    image: `${root}b_Wood.png`,
    gender: 2,
  },
  {
    index: 41,
    brand: '불가리',
    title: '오 파퓨메 오 떼 블랑 오 드 코롱 스프레이(75ml)',
    etitle: 'Eau Parfumee au the blanc',
    price: 128000,
    strong: 1,
    top: 1,
    second: 3,
    last: 3,
    des: '부드럽게 퍼지며 마음을 달래주는 진귀한 화이트 히말라얀 티 스타일의 남성 및 여성용 오 드 코롱',
    image: `${root}b_Parfume.png`,
    gender: 3,
  },
  {
    index: 42,
    brand: '불가리',
    title: '스플랜디다 불가리 쟈스민 느와 오 드 퍼퓸',
    etitle: 'Spledida Bvlgari jasmin Noir',
    price: 137000,
    strong: 4,
    top: 4,
    second: 2,
    last: 2,
    des: '극도로 드라이한 우디 향과 순수하고 호화로운 플로럴 노트가 자아내는 대조의 조화',
    image: `${root}b_Spledida.png`,
    gender: 3,
  },
  {
    index: 43,
    brand: '불가리',
    title: '불가리 옴니아 크리스탈린 오 드 뚜왈렛(65ml)',
    etitle: 'Bvlgari Omnia Crystalline',
    price: 126000,
    strong: 3,
    top: 1,
    second: 2,
    last: 3,
    des: '연꽃의 청초함, 배의 신선한 과일 향 그리고 발사 우드의 크리미한 향이 완성하는 화사한 오 드 뚜왈렛',
    image: `${root}b_Crystalline.png`,
    gender: 3,
  },
  {
    index: 44,
    brand: '불가리',
    title: '스플랜디다 불가리 매그놀리아 센슈얼 오 드 퍼퓸',
    etitle: 'Splendida Bvlgari Magnolia Sensuel',
    price: 126000,
    strong: 4,
    top: 2,
    second: 2,
    last: 2,
    des: '천상의 아름다움을 펼쳐내는 섬세하면서도 강렬한 매그놀리아의 풍성하고 센슈얼한 프래그런스',
    image: `${root}b_Magnolia.png`,
    gender: 3,
  },
  {
    index: 45,
    brand: '크리드',
    title: '크리드 어벤투스 오 드 퍼퓸',
    etitle: 'CREED AVENTUS',
    price: 338000,
    strong: 4,
    top: 2,
    second: 2,
    last: 2,
    des: '첫향은 파인애플의 향으로 시트러스와 프루티하게 시작하지만 살짝 무겁게 느껴져 섹시하면서도 강하지 않은 향으로 시작한다. 그 후에 머스크와 우디의 부드러움이 추가되어 우아하고 고급스럽게 마무리 된다',
    image: `${root}cr_Aventus.png`,
    gender: 2,
  },
  {
    index: 46,
    brand: '크리드',
    title: '크리드 밀레지움 임페리얼(75ml)',
    etitle: 'CREED MILLÉSIME IMPÉRIAL',
    price: 368000,
    strong: 4,
    top: 2,
    second: 4,
    last: 2,
    des: '달달한 프루티와 약간의 물기 머금은 짠 소금향으로 시작하여 코 끝에 스치는 신선하면서도 짭짤한 물기 머금은 바닷바람이 느껴집니다. 신선한 과일을 먹으며 바닷바람을 만끽하고 있는 느낌이 듭니다.',
    image: `${root}cr_Millesime.png`,
    gender: 2,
  },
  {
    index: 47,
    brand: '크리드',
    title: '크리드 어벤투스 포 허',
    etitle: 'Creed Aventus for Her',
    price: 320000,
    strong: 4,
    top: 2,
    second: 2,
    last: 5,
    des: '역사적으로 모든 이들에게 영향력을 발휘했던 강인하고 자신감 넘치는 여성 리더들로부터 영감을 받아 3년간 준비한 끝에 출시된 향수시간이 지날수록 탑노트가 날아가면서 은은한 머스크와 우디향이 조화롭게 어우러져 차분하고 분위기 있는 향이 납니다.',
    image: `${root}cr_Her.png`,
    gender: 1,
  },
  {
    index: 48,
    brand: '크리드',
    title: '크리드 그린 아이리쉬 트위드',
    etitle: 'CREED GREEN IRISH TWEED',
    price: 338000,
    strong: 4,
    top: 2,
    second: 4,
    last: 2,
    des: '19세기 신사 컨트리 트위드처럼 세련되고 클래식하며 여유로운 남성의 매력, 은은하게 피어오르는 상쾌한 향은 무엇에도 얽매이지 않는 남자의 자유를 그려냅니다.',
    image: `${root}cr_Green.png`,
    gender: 2,
  },
  {
    index: 49,
    brand: '크리드',
    title: '크리드 실버 마운틴 워터',
    etitle: 'CREED SILVER MOUNTAIN WATER',
    price: 338000,
    strong: 4,
    top: 2,
    second: 4,
    last: 2,
    des: '알프스 산맥의 시원하고 상쾌한 공기에서 영감을 받아 탄생한 청량하고 상쾌한 향입니다. 티 노트의 반짝이는 향은 우리를 어느 먼곳으로 인도해줄거에요.',
    image: `${root}cr_Silver.png`,
    gender: 2,
  },
  {
    index: 50,
    brand: '크리드',
    title: '크리드 러브 인 화이트(75ml)',
    etitle: 'CREED LOVE IN WHITE',
    price: 339000,
    strong: 4,
    top: 2,
    second: 2,
    last: 5,
    des: '세계의 화합과 평화를 담은 향수, 5대륙의 에센스를 선택해서 조향하였습니다. 순수한 자유 고요한 꿈 평화롭고 부드러운 사랑의 꽃향기를 담은 향수',
    image: `${root}cr_Love.png`,
    gender: 3,
  },
];
