const root = './images/items/';
export const Perfume = [
  {
    index: 0,
    brand: '조말론',
    title: '라임 바질 앤 만다린 코롱',
    etitle: 'Lime Basil & Mandarin Cologne',
    price: 139000,
    strong: 1,
    top: 2,
    second: 3,
    last: 2,
    des: '조 말론 런던의 시그니처 향. 카리브해의 산들바람에서 실려온 듯한 라임향에 톡 쏘는 바질과 향기로운 백리향이 더해져 독특한 조합을 만들어 냅니다. 현대적인 감각의 클래식한 향입니다.',
    image: `${root}j_Basil.png`,
    gender: 3,
  },
  {
    index: 1,
    brand: '조말론',
    title: '잉글리쉬 페어 앤 프리지아 코롱',
    etitle: 'English Pear & Freesia Cologne',
    price: 139000,
    strong: 1,
    top: 4,
    second: 2,
    last: 2,
    des: '가을의 정수. 화이트 프리지아 부케향에 이제 막 익은 배의 신선함을 입히고 호박, 파출리, 우디향으로 은은함을 더했습니다.',
    image: `${root}j_EnglishPear.png`,
    gender: 3,
  },
  {
    index: 2,
    brand: '조말론',
    title: '피오니 앤 블러쉬 스웨이드 코롱',
    etitle: 'Peony & Blush Suede Cologne',
    price: 139000,
    strong: 1,
    top: 4,
    second: 2,
    last: 4,
    des: '꽃의 귀족, 작약의 화려함을 담은 향. 화려하게 핀 작약에 더해진 붉은 사과의 향기로운 과즙과 순수한 자스민, 장미 그리고 카네이션, 블러쉬 스웨이드의 부드러운 관능미가 여운을 남깁니다.',
    image: `${root}j_Peony.png`,
    gender: 3,
  },
  {
    index: 3,
    brand: '조말론',
    title: '우드 세이지 앤 씨 솔트 코롱',
    etitle: 'Wood Sage & Sea Salt Cologne',
    price: 139000,
    strong: 1,
    top: 5,
    second: 4,
    last: 2,
    des: '바람부는 해안을 따라 걸으며 일상을 벗어나보세요. 하얗게 부서지는 파도, 소금기를 머금은 신선한 바다 공기. 험준한 절벽에서 느껴지는 투박한 자연의 향기와 세이지의 우디한 흙 내음이 어우러져 자유롭고 활기찬 에너지와 즐거움이 가득합니다.',
    image: `${root}j_WoodSage.png`,
    gender: 3,
  },
  {
    index: 4,
    brand: '조말론',
    title: '머르 앤 통카 코롱 인텐스',
    etitle: 'Myrrh & Tonka Cologne Intense',
    price: 189000,
    strong: 2,
    top: 4,
    second: 5,
    last: 5,
    des: '꽃의 귀족, 작약의 화려함을 담은 향. 화려하게 핀 작약에 더해진 붉은 사과의 향기로운 과즙과 순수한 자스민, 장미 그리고 카네이션, 블러쉬 스웨이드의 부드러운 관능미가 여운을 남깁니다.',
    image: `${root}j_Myrrt.png`,
    gender: 3,
  },
  {
    index: 5,
    brand: '조말론',
    title: '허니서클 앤 다바나 코롱',
    etitle: 'Honeysuckle & Davana Cologne',
    price: 139000,
    strong: 1,
    top: 4,
    second: 2,
    last: 2,
    des: '영국 전원 지대에 물결치듯이 피어 오르는 야생 허니서클은 휘감듯이 피어 오르며 어둠이 깔리면 더욱 매력적으로 빛납니다. 과일 향의 반전을 지닌 다바나의 아로마 향, 여기에 로즈 향이 가미되어 더욱 신선해 집니다. ',
    image: `${root}j_Honeysuckle.png`,
    gender: 3,
  },
  {
    index: 6,
    brand: '조말론',
    title: '미모사 앤 카다멈 코롱',
    etitle: 'Mimosa & Cardamom Cologne',
    price: 139000,
    strong: 1,
    top: 2,
    second: 2,
    last: 5,
    des: '골드빛 미모사의 달콤한 향이 이제 막 으깬 카다멈의 스파이시함 위로 안개처럼 피어 오릅니다. 새벽에 수확한 다마스크 로즈와 파우더리한 헬리토오프 아래 크리미한 통카와 부드러운 샌달우드 향이 물결치듯 퍼져 나가며 따뜻한 천상의 향으로 당신을 매혹시킵니다.',
    image: `${root}j_Mimosa.png`,
    gender: 3,
  },
  {
    index: 7,
    brand: '조말론',
    title: '레드 로즈 코롱',
    etitle: 'Red Roses Cologne',
    price: 139000,
    strong: 1,
    top: 2,
    second: 2,
    last: 5,
    des: '현대적인 로맨스의 상징. 세상에서 가장 아름다운 일곱가지 장미가 조합된 관능적인 향입니다. 으깬 바이올렛 잎과 약간의 레몬이 조합되어 신선한 부케향을 발산합니다. 놀라울 정도로 투명하고 순수한 향을 선사합니다.',
    image: `${root}j_Redroses.png`,
    gender: 3,
  },
  {
    index: 8,
    brand: '조말론',
    title: '와일드 블루벨 코롱',
    etitle: 'Wild Bluebell Cologne',
    price: 139000,
    strong: 1,
    top: 1,
    second: 1,
    last: 3,
    des: '숲 속 깊은 곳에서 빛나고 있는 사파이어. 이슬 맺힌 블루벨의 은은하고 달콤한 향에 릴리와 들장미 향의 조화가 최면을 걸 듯 마음을 사로잡습니다.',
    image: `${root}j_Wildblubell.png`,
    gender: 3,
  },
  {
    index: 9,
    brand: '조말론',
    title: '스칼렛 포피 코롱 인텐스',
    etitle: 'Scarlet Poppy Cologne Intense',
    price: 191000,
    strong: 2,
    top: 4,
    second: 2,
    last: 5,
    des: ' 아시아 야생의 초원에서 자라난 화려한 ‘꽃양귀비’ (Great Scarlet Poppy)에서 영감을 받아 탄생한 향 입니다. 부드러운 아이리스 꽃 향, 보리, 그리고 통카 빈 노트가 달콤한 퇴폐미를 강조하고, 과즙이 가득한 무화과 어코드가 향을 한층 풍부하게 만들어줍니다.',
    image: `${root}j_Scalepoppy.png`,
    gender: 3,
  },
  {
    index: 10,
    brand: '샤넬',
    title: '샹스 오 후레쉬',
    etitle: 'CHANCE EAU FRAÎCHE',
    price: 137000,
    strong: 3,
    top: 2,
    second: 2,
    last: 2,
    des: '샤넬의 코’로 불리우는 자크 뽈쥬는 기대하지 못했던 환희의 샹스를 더욱 대담하며 환상으로 가득 찬 향조로 재해석하였습니다.기대하지 못했던 환희의 플로랄 향조는 톡 쏘는듯 상큼하고 생동감 있는 플로랄 향조가 되었습니다.',
    image: `${root}c_Fresh.png`,
    gender: 1,
  },
  {
    index: 11,
    brand: '샤넬',
    title: '알뤼르 오드 빠르펭',
    etitle: 'ALLURE SENSUELLE',
    price: 168000,
    strong: 4,
    top: 2,
    second: 2,
    last: 2,
    des: '마드모아젤 샤넬이 정의한 고결한 품격. 있는 그대로의 카리스마. 모든 여성을 위해 여섯 가지의 향이 서로 다르게 표현되는 플로랄-프레쉬-엠버리 향수. 여성이 지닌 각자의 고유한 매력을 강조합니다.',
    image: `${root}c_Allure.png`,
    gender: 3,
  },
  {
    index: 12,
    brand: '샤넬',
    title: '샹스 오 비브 오드 뚜왈렛',
    etitle: 'CHANCE EAU VIVE',
    price: 137000,
    strong: 3,
    top: 2,
    second: 2,
    last: 1,
    des: '자몽과 블러드 오렌지의 상큼한 향이 더해진 생기 넘치는 플로랄 계열의 향수. 탑 노트의 즐거운 향을 경험해 보세요. 뒤이은 쟈스민 향은 섬세하게 여성성을 드러내고 맑고 투명한 시더-아이리스 향으로 은은하고 우아한 마무리를 선사합니다',
    image: `${root}c_Vive.png`,
    gender: 1,
  },
  {
    index: 13,
    brand: '샤넬',
    title: '샹스 오 땅드르',
    etitle: 'CHANCE EAU TENDRE',
    price: 137000,
    strong: 3,
    top: 2,
    second: 2,
    last: 3,
    des: '순수한 향기의 시, 프루티-플로랄 향, 부드러움의 달콤한 물결,자몽과 모과 향이 쟈스민과 어우러져 화이트 머스크의 둥글고 여성적인 노트에 의해 따스함이 더해집니다.이 새롭고 거부할 수 없는 매혹적인 행운의 향은 행복을 믿고 기회를 놓치지 않는 낙천적인 여성의 향기입니다.',
    image: `${root}c_Tendre.png`,
    gender: 1,
  },
  {
    index: 14,
    brand: '샤넬',
    title: '코코 마드모아젤',
    etitle: 'COCO MADEMOISELLE',
    price: 168000,
    strong: 4,
    top: 2,
    second: 2,
    last: 5,
    des: '오리엔탈-훌로랄. 따뜻하고도 관능적인 향. 후레쉬하고 관능적이며 섹시하고 세련된 향이 완벽한 모던함을 표현합니다',
    image: `${root}c_Coco.png`,
    gender: 1,
  },
  {
    index: 15,
    brand: '샤넬',
    title: '샤넬 No.5',
    etitle: 'No.5',
    price: 168000,
    strong: 4,
    top: 2,
    second: 2,
    last: 3,
    des: 'N°5, 여성미의 정수. 알데하이드 플로랄 부케 향수는 미니멀한 디자인이 돋보이는 아이코닉 보틀로 선보입니다. 시간을 초월한 유서 깊은 샤넬의 아이콘.',
    image: `${root}c_no5.png`,
    gender: 1,
  },
  {
    index: 16,
    brand: '샤넬',
    title: '알뤼르 옴므 스포츠',
    etitle: 'ALLURE HOMME SPORT',
    price: 110000,
    strong: 3,
    top: 2,
    second: 4,
    last: 2,
    des: '신선한 우디 향수.수분감으로 가득한 신선하고 감각적인 노트가 역동성을 분출하는 남성성을 표현합니다.',
    image: `${root}c_Sport.png`,
    gender: 2,
  },
  {
    index: 17,
    brand: '샤넬',
    title: '가브리엘 샤넬',
    etitle: 'GABRIELLE CHANEL',
    price: 168000,
    strong: 4,
    top: 2,
    second: 5,
    last: 3,
    des: '가브리엘 샤넬 오 드 빠르펭은 빛을 머금은 향수입니다. 이국적이고 강렬한 쟈스민, 생동감 넘치는 과일 향이 매력적인 일랑일랑, 신선하고 반짝이는 오렌지 블라썸, 그리고 부드럽고 섬세한 그라스 튜베로즈를 포함한 4가지의 꽃향기가 어우러져 완성된 순수한 플로랄 향을 선사합니다.',
    image: `${root}c_Gabrielle.png`,
    gender: 1,
  },
  {
    index: 18,
    brand: '샤넬',
    title: '블루 드 샤넬',
    etitle: 'BLEU DE CHANEL',
    price: 127000,
    strong: 4,
    top: 4,
    second: 5,
    last: 2,
    des: '블루 드 샤넬 오 드 빠르펭은 앰버리한 시더와 베네수엘라 통카빈이 뉴칼레도니아 샌달우드의 우아하고 깊이있는 향과 조화를 이루어 따뜻하고 관능적인 느낌을 자아내는 우디 아로마틱 향수입니다.',
    image: `${root}c_Blue.png`,
    gender: 2,
  },
  {
    index: 19,
    brand: '딥디크',
    title: '도 손 오드 퍼퓸(75ml)',
    etitle: 'DO SON EAU DE PARFUM',
    price: 235000,
    strong: 4,
    top: 4,
    second: 1,
    last: 2,
    des: '큰 항구도시 하이퐁의 습한 열기로부터 멀리 떨어져 있는 도손의 공기는 좀 더 시원했습니다. 은은한 향신료 향이 어우러진 황홀한 튜베로즈 향기가 해풍에 실려갑니다. ',
    image: `${root}d_Doson.png`,
    gender: 3,
  },
  {
    index: 20,
    brand: '딥디크',
    title: '베티베이리오 오드 뚜왈렛',
    etitle: 'VETYVERIO EDT',
    price: 143000,
    strong: 3,
    top: 2,
    second: 2,
    last: 5,
    des: '플로리다산 자몽과 터키산 장미의 향기로운 조화를 이루는 향수, 우디향의 향수로 시원하고 풀향이 나는 것이 특징! ',
    image: `${root}d_Vetyverio.png`,
    gender: 3,
  },
  {
    index: 21,
    brand: '딥디크',
    title: '플레드 드뽀 오드 퍼퓸(75ml)',
    etitle: 'fleur de peau',
    price: 235000,
    strong: 4,
    top: 3,
    second: 5,
    last: 3,
    des: '피부의 꽃이라는 뜻으로 머스크와 아이리스가 어우러진 부드럽고 파우더리한 향수 첫향은 강하다는 의견이 많지만 잔향이 좋아 인기가 많다',
    image: `${root}d_Fleur.png`,
    gender: 3,
  },
  {
    index: 22,
    brand: '딥디크',
    title: '필로시코스 오드 뚜왈렛(75ml)',
    etitle: 'Philosykos',
    price: 235000,
    strong: 3,
    top: 4,
    second: 4,
    last: 2,
    des: '그린 우디 플로랄 계열, 내추럴한 무화과 향기 무화과 열매뿐만 아니라 나무 향과 따스한 흙향도 함께 느껴지는 향수, 산뜻하고 달달한 것이 특징',
    image: `${root}d_Philosykos.png`,
    gender: 3,
  },
  {
    index: 23,
    brand: '딥디크',
    title: '탐 다오 오드 퍼퓸',
    etitle: 'Tam dao',
    price: 143000,
    strong: 4,
    top: 2,
    second: 3,
    last: 2,
    des: '복잡했던 마을을 한꺼번에 달래줄 법한, 신선한 공기 가득한 숲속의 사찰 마루에서 날법한 나무향입니다. 차분한 느낌이 특징',
    image: `${root}d_Tam.png`,
    gender: 3,
  },
  {
    index: 24,
    brand: '딥디크',
    title: '롬보르 단 로 오드 뚜왈렛(75ml)',
    etitle: `L'OMBRE DANS`,
    price: 235000,
    strong: 3,
    top: 3,
    second: 4,
    last: 5,
    des: '시원한 향을 주는 블랙 커런트 잎과 헤드 노트인 불가리안 로즈가 완벽한 조화를 이뤄 럭셔리 하면서도 세련된 향을 선사한다.',
    image: `${root}d_L.png`,
    gender: 3,
  },
  {
    index: 25,
    brand: '딥디크',
    title: '오 데 썽 오드 뚜왈렛',
    etitle: 'EAU DES SENS',
    price: 143000,
    strong: 3,
    top: 2,
    second: 5,
    last: 2,
    des: '오렌지 나무 한그루를 감각적으로 담아내 과육의 풍미와 달콤함, 초록색 줄기의 싱그러움이 모두 느껴지는 향수, 오렌지향과 우드, 머스크향이 조화된 향수',
    image: `${root}d_Des.png`,
    gender: 3,
  },
  {
    index: 26,
    brand: '딥디크',
    title: '오 로즈 오드 뚜왈렛',
    etitle: 'EAU ROSE',
    price: 143000,
    strong: 3,
    top: 3,
    second: 2,
    last: 3,
    des: '장미 에센스 중 가장 귀한 센티폴리아 장미가 하트 노트로 사용되어 매혹적인 플로럴 향이 공기의 숨결을 따라 은은하게 퍼져나가는 향수',
    image: `${root}d_Rose.png`,
    gender: 3,
  },
  {
    index: 27,
    brand: '구찌',
    title: '[구찌 길티] 오 드 퍼퓸 인텐스 뿌르 팜므',
    etitle: 'Gucci Guilty Eau de Parfum Intense Pour Femme',
    price: 160000,
    strong: 4,
    top: 3,
    second: 2,
    last: 3,
    des: '사회의 규범과 관념에 얽매이지 않는 사랑을 선언하고자 하는 이들을 위한 향수에 강렬함을 한층 더합니다. 마음이 서로 잘 맞는 연인을 연결하는 상징으로 디자인된 구찌 길티 오 드 퍼퓸 인텐스 뿌르 팜므는 구찌 길티 뿌르 팜므의 핵심 시그니처 향을 재해석한 앰버 플로라 우디 향이 특징적입니다.',
    image: `${root}g_Guiltypourfemme.png`,
    gender: 1,
  },
  {
    index: 28,
    brand: '구찌',
    title: '[알케미스트 가든] 오 드 퍼퓸 A Gloaming Night(100ml) ',
    etitle: 'The Alchemist’s Garden A Gloaming Night',
    price: 440000,
    strong: 4,
    top: 4,
    second: 2,
    last: 1,
    des: '아름다운 일몰의 컬러에서 영감을 받은 향은 핑크, 퍼플, 피치, 레드 컬러의 하늘이 수평선 위로 으스름을 만들어내듯이 서로 어우러져 특별한 아로마를 완성합니다. 알레산드로 미켈레의 창의적인 디렉션을 통해 마스터 조향사인 알베르토 모리야스(Alberto Morillas)가 블렌딩하여 선보이는 커스텀 가능한 이 상품은 오 드 퍼퓸, 퍼퓸 오일, 퍼퓸 워터로 만나보실 수 있습니다.',
    image: `${root}g_Gloamingnight.png`,
    gender: 3,
  },
  {
    index: 29,
    brand: '구찌',
    title: '[알케미스트 가든] 오 드 퍼퓸 1921(100ml) ',
    etitle: 'The Alchemist’s Garden 1921',
    price: 440000,
    strong: 4,
    top: 4,
    second: 4,
    last: 2,
    des: 'Gucci 100주년을 기념하여 1921이라는 이름의 새로운 스페셜 향수가 알케미스트 가든 럭셔리 컬렉션에 추가되었습니다. 상징적인 네롤리 플라워를 중심으로 구성된 향수는 하우스의 또 다른 헤리티지인 구찌가 창립된 피렌체에서 재배한 시트론 레몬향이 돋보입니다.',
    image: `${root}g_1921.png`,
    gender: 3,
  },
  {
    index: 30,
    brand: '구찌',
    title:
      '[알케미스트 가든]오 드 퍼퓸 A Chant for the Nymph,프랑지파니(100ml)',
    etitle: 'A Chant for the Nymph, Frangipani',
    price: 440000,
    strong: 4,
    top: 1,
    second: 2,
    last: 5,
    des: '꽃으로 가득한 열대우림에서 영감을 얻은 프랑지파니 향수입니다. 따뜻한 밤에 피어나는 상쾌하고 오래 지속되는 향으로 불멸성을 상징하는 프랑지파니 꽃이 향수를 정의하며, 한여름 밤의 꿈에 등장하는 오래 전에 잊혀진 신화적인 존재, 님프의 이야기를 떠올리게 합니다.',
    image: `${root}g_Nymph.png`,
    gender: 3,
  },
  {
    index: 31,
    brand: '구찌',
    title: '[구찌 블룸] 오 드 퍼퓸 암브로시아 디 피오리',
    etitle: 'Gucci Bloom Ambrosia di Fiori',
    price: 160000,
    strong: 4,
    top: 3,
    second: 2,
    last: 3,
    des: '고대 시대의 연회를 연상시키는 암브로시아는 그리스 신들의 음료로, 마시는 사람에게 영생을 준다고 전해져 내려옵니다. 이러한 전설이 담겨있는 이름과 신비로운 마법에서 유래된 향수에 생기 있는 향을 더하여 탄생하였습니다. 오리지널 구찌 블룸 오드 퍼퓸의 세가지 조합인 자스민 봉오리, 튜베로즈, 그리고 랑군 덩굴에 고대 그리스 로마 사람들에게 최고로 여겨 졌던 아이리스 뿌리에서 추출 한 벨베티 오리스와 가장 풍성한 향을 뿜어내는 장미 품종인 다마스크 로즈 향을 더했습니다. ',
    image: `${root}g_Ambrosia.png`,
    gender: 1,
  },
  {
    index: 32,
    brand: '구찌',
    title: '[구찌 블룸] 오 드 퍼퓸 프로푸모 디 피오리',
    etitle: 'Gucci Bloom Profumo di Fiori',
    price: 160000,
    strong: 4,
    top: 3,
    second: 2,
    last: 3,
    des: '클래식한 구찌 블룸을 재해석한 프로모프 디 피오리는 아라비아 재스민과 튜베로즈를 블렌딩해서 중독성 있는 향기가 은은히 퍼져나갑니다.',
    image: `${root}g_Profumo.png`,
    gender: 1,
  },
  {
    index: 33,
    brand: '구찌',
    title: '[구찌 길티]오 드 퍼퓸 뿌르 옴므',
    etitle: 'Gucci Guilty Parfum Pour Homme',
    price: 119000,
    strong: 4,
    top: 3,
    second: 2,
    last: 2,
    des: '마음이 서로 잘 맞는 연인을 연결하는 상징으로 디자인된 구찌 길티 퍼퓸 뿌르 옴므는 구찌 길티 뿌르 옴므의 시그니처 향을 더욱 강렬하게 표현한 우디 아로마틱 앰버 향이 특징적입니다.',
    image: `${root}g_Pourhomme.png`,
    gender: 2,
  },
  {
    index: 34,
    brand: '구찌',
    title: '오 드 퍼퓸 구찌 메모아 뒨 오더(100ml)',
    etitle: 'Gucci Mémoire d`une Odeur',
    price: 201000,
    strong: 4,
    top: 3,
    second: 6,
    last: 2,
    des: '16세기와 17세기 로마의 테라스가 있는 정원에서 자란 로만 카모마일의 싱그러운 아로마 향과 밤이면 더욱 강한 향을 자아내는 인디언 코럴 자스민의 향을 블렌딩하였습니다. 머스크 향이 향수에 깊이를 더하고, 시더우드와 샌들우드가 강렬함을 더합니다.',
    image: `${root}g_Memoire.png`,
    gender: 2,
  },
  {
    index: 35,
    brand: '구찌',
    title: '[구찌 길티] 오 드 뚜왈렛 뿌르 옴므',
    etitle: 'Gucci Guilty Eau de toilette Pour Homme',
    price: 103000,
    strong: 3,
    top: 2,
    second: 4,
    last: 2,
    des: '미스테리하고 관능적이며 은밀한 매력을 현대적인 감성으로 풀어낸 파촐리의 베이스 노트. 강렬한 남성성을 느낄 수 있는 시더 우드의 드라이 다운 노트로 구성되어 있습니다. 구찌 길티 뿌르 옴므의 청동 도금된 향수 병과 뚜껑은 웜톤 퍼플 그레이 색상의 향수와 조화를 이룹니다.',
    image: `${root}g_Guiltytoilette.png`,
    gender: 2,
  },
  {
    index: 36,
    brand: '불가리',
    title: '오 드 뚜왈렛 옴니아 핑크 사파이어(40ml)',
    etitle: 'Eau de toilette Omnia Pink Sapphire',
    price: 113000,
    strong: 3,
    top: 4,
    second: 1,
    last: 3,
    des: '플로럴 계열의 옴니아 핑크 사파이어는 향수에 영감이 되어준 젬스톤의 컬러처럼 눈부신 햇살이 내리쬐는 어느 화창한 날의 축제를 떠올리게 하는, 열정적이면서도 독특한 향을 선사합니다. 본질에 맞게 정확히 어우러진 성분들이 강렬한 아름다움과 감각적인 풍부함이 고스란히 느껴지는 자연의 힘을 구현합니다.',
    image: `${root}b_Omniapink.png`,
    gender: 1,
  },
  {
    index: 37,
    brand: '불가리',
    title: '로즈 골데아 오 드 퍼퓸',
    etitle: 'Rose Goldea Bvlgari',
    price: 146000,
    strong: 4,
    top: 2,
    second: 2,
    last: 2,
    des: '불가리는 화려한 장미와 섬세한 머스크로 여성스러운 감성을 자아내는 로즈 골데아를 선보입니다. 불가리의 상징과도 같은 세르펜티 컬렉션에서 영감을 받은 로즈 골데아는 거부할 수 없는 열정적인 사랑을 상징하는 대담한 매력의 주얼리처럼 화려하게 피어납니다.',
    image: `${root}b_Rose.png`,
    gender: 1,
  },
  {
    index: 38,
    brand: '불가리',
    title: '로즈 골데아 블라썸 딜라이트 오 드 퍼퓸',
    etitle: 'ROSE GOLDEA BLOSSOM DELIGHT',
    price: 146000,
    strong: 4,
    top: 3,
    second: 2,
    last: 3,
    des: '부드러운 꽃잎에서부터 강렬한 우아함을 품은 하트 노트에 이르기까지, 로즈 골데아 블러썸 딜라이트 오 드 퍼퓸은 계속해서 성장을 거듭하는 로즈버드의 생기를 재현하며 더욱더 화려하게 피어나는 장미 특유의 매력을 온전히 담아냅니다.',
    image: `${root}b_Goldea.png`,
    gender: 1,
  },
  {
    index: 39,
    brand: '불가리',
    title: '불가리 뿌르 옴므 익스트림 오 드 뚜왈렛',
    etitle: 'BVLGARI POUR HOMME',
    price: 89000,
    strong: 3,
    top: 2,
    second: 3,
    last: 5,
    des: '불가리 뿌르 옴므 익스트림은 불가리 뿌르 옴므를 재해석한 신선하고 생동감 넘치는 향수로, 시간을 초월한 세련된 남성의 품격을 표현하는 전형적인 표상입니다.',
    image: `${root}b_Homme.png`,
    gender: 2,
  },
  {
    index: 40,
    brand: '불가리',
    title: '맨 우드 에센스 오 드 퍼퓸(60ml)',
    etitle: 'Man Wood Essence EDP',
    price: 100000,
    strong: 4,
    top: 2,
    second: 4,
    last: 2,
    des: '시더, 사이프러스, 베티버와 같은 최고급 에센스 그리고 따뜻한 태양 빛을 닮은 벤조인 레진 노트가 아름답게 공명하는 네오 우디 계열의 향수',
    image: `${root}b_Wood.png`,
    gender: 2,
  },
  {
    index: 41,
    brand: '불가리',
    title: '오 파퓨메 오 떼 블랑 오 드 코롱 스프레이(75ml)',
    etitle: 'Eau Parfumee au the blanc',
    price: 128000,
    strong: 1,
    top: 1,
    second: 3,
    last: 3,
    des: '부드럽게 퍼지며 마음을 달래주는 진귀한 화이트 히말라얀 티 스타일의 남성 및 여성용 오 드 코롱',
    image: `${root}b_Parfume.png`,
    gender: 3,
  },
  {
    index: 42,
    brand: '불가리',
    title: '스플랜디다 불가리 쟈스민 느와 오 드 퍼퓸',
    etitle: 'Spledida Bvlgari jasmin Noir',
    price: 137000,
    strong: 4,
    top: 4,
    second: 2,
    last: 2,
    des: '극도로 드라이한 우디 향과 순수하고 호화로운 플로럴 노트가 자아내는 대조의 조화',
    image: `${root}b_Spledida.png`,
    gender: 3,
  },
  {
    index: 43,
    brand: '불가리',
    title: '불가리 옴니아 크리스탈린 오 드 뚜왈렛(65ml)',
    etitle: 'Bvlgari Omnia Crystalline',
    price: 126000,
    strong: 3,
    top: 1,
    second: 2,
    last: 3,
    des: '연꽃의 청초함, 배의 신선한 과일 향 그리고 발사 우드의 크리미한 향이 완성하는 화사한 오 드 뚜왈렛',
    image: `${root}b_Crystalline.png`,
    gender: 3,
  },
  {
    index: 44,
    brand: '불가리',
    title: '스플랜디다 불가리 매그놀리아 센슈얼 오 드 퍼퓸',
    etitle: 'Splendida Bvlgari Magnolia Sensuel',
    price: 126000,
    strong: 4,
    top: 2,
    second: 2,
    last: 2,
    des: '천상의 아름다움을 펼쳐내는 섬세하면서도 강렬한 매그놀리아의 풍성하고 센슈얼한 프래그런스',
    image: `${root}b_Magnolia.png`,
    gender: 3,
  },
  {
    index: 45,
    brand: '크리드',
    title: '크리드 어벤투스 오 드 퍼퓸',
    etitle: 'CREED AVENTUS',
    price: 338000,
    strong: 4,
    top: 2,
    second: 2,
    last: 2,
    des: '첫향은 파인애플의 향으로 시트러스와 프루티하게 시작하지만 살짝 무겁게 느껴져 섹시하면서도 강하지 않은 향으로 시작한다. 그 후에 머스크와 우디의 부드러움이 추가되어 우아하고 고급스럽게 마무리 된다',
    image: `${root}cr_Aventus.png`,
    gender: 2,
  },
  {
    index: 46,
    brand: '크리드',
    title: '크리드 밀레지움 임페리얼(75ml)',
    etitle: 'CREED MILLÉSIME IMPÉRIAL',
    price: 368000,
    strong: 4,
    top: 2,
    second: 4,
    last: 2,
    des: '달달한 프루티와 약간의 물기 머금은 짠 소금향으로 시작하여 코 끝에 스치는 신선하면서도 짭짤한 물기 머금은 바닷바람이 느껴집니다. 신선한 과일을 먹으며 바닷바람을 만끽하고 있는 느낌이 듭니다.',
    image: `${root}cr_Millesime.png`,
    gender: 2,
  },
  {
    index: 47,
    brand: '크리드',
    title: '크리드 어벤투스 포 허',
    etitle: 'Creed Aventus for Her',
    price: 320000,
    strong: 4,
    top: 2,
    second: 2,
    last: 5,
    des: '역사적으로 모든 이들에게 영향력을 발휘했던 강인하고 자신감 넘치는 여성 리더들로부터 영감을 받아 3년간 준비한 끝에 출시된 향수시간이 지날수록 탑노트가 날아가면서 은은한 머스크와 우디향이 조화롭게 어우러져 차분하고 분위기 있는 향이 납니다.',
    image: `${root}cr_Her.png`,
    gender: 1,
  },
  {
    index: 48,
    brand: '크리드',
    title: '크리드 그린 아이리쉬 트위드',
    etitle: 'CREED GREEN IRISH TWEED',
    price: 338000,
    strong: 4,
    top: 2,
    second: 4,
    last: 2,
    des: '19세기 신사 컨트리 트위드처럼 세련되고 클래식하며 여유로운 남성의 매력, 은은하게 피어오르는 상쾌한 향은 무엇에도 얽매이지 않는 남자의 자유를 그려냅니다.',
    image: `${root}cr_Green.png`,
    gender: 2,
  },
  {
    index: 49,
    brand: '크리드',
    title: '크리드 실버 마운틴 워터',
    etitle: 'CREED SILVER MOUNTAIN WATER',
    price: 338000,
    strong: 4,
    top: 2,
    second: 4,
    last: 2,
    des: '알프스 산맥의 시원하고 상쾌한 공기에서 영감을 받아 탄생한 청량하고 상쾌한 향입니다. 티 노트의 반짝이는 향은 우리를 어느 먼곳으로 인도해줄거에요.',
    image: `${root}cr_Silver.png`,
    gender: 2,
  },
  {
    index: 50,
    brand: '크리드',
    title: '크리드 러브 인 화이트(75ml)',
    etitle: 'CREED LOVE IN WHITE',
    price: 339000,
    strong: 4,
    top: 2,
    second: 2,
    last: 5,
    des: '세계의 화합과 평화를 담은 향수, 5대륙의 에센스를 선택해서 조향하였습니다. 순수한 자유 고요한 꿈 평화롭고 부드러운 사랑의 꽃향기를 담은 향수',
    image: `${root}cr_Love.png`,
    gender: 3,
  },
  {
    index: 51,
    brand: '버버리',
    title: 'Her 블로섬 오드트왈렛',
    etitle: 'Her blossom',
    price: 116000,
    strong: 3,
    top: 2,
    second: 3,
    last: 2,
    des: '화사한 매화꽃 노트가 어우러진 오리지널 오드퍼퓸의 구르망 시그니처 향수. 상큼한 만다린과 크리미한 샌들우드 그리고 편안함을 주는 머스크 노트가 따뜻하고 풍부한 향을 선사합니다.',
    image: `${root}bb_Blossom.png`,
    gender: 1,
  },
  {
    index: 52,
    brand: '버버리',
    title: 'Her 런던 드림 오드퍼퓸',
    etitle: 'Her London Dream',
    price: 129000,
    strong: 4,
    top: 5,
    second: 2,
    last: 3,
    des: '모던하고 릴랙스한 라이프 스타일이 연상되는 화사하고 매력적인 향의 Her 런던 드림은 시그니처 Her의 향에 레몬과 프레시 진저 톱 노트, 로맥틱한 장미와 피오니의 미들 노트를 더해 새롭게 재해석되었습니다.',
    image: `${root}bb_London.png`,
    gender: 1,
  },
  {
    index: 53,
    brand: '버버리',
    title: 'Her 오드퍼퓸',
    etitle: 'Her eau de Parfum',
    price: 129000,
    strong: 4,
    top: 4,
    second: 5,
    last: 2,
    des: '에포트리스 스타일, 에너제틱, 낙관적인 애티튜드, 모험심과 대담함, 아름답고 번화하며 창조적인 상상력이 넘치는 도시, 자유롭고 풍요로운 라이프를 표현했습니다.',
    image: `${root}bb_Her.png`,
    gender: 1,
  },
  {
    index: 54,
    brand: '버버리',
    title: 'Her 인텐스 오드 퍼퓸',
    etitle: 'Her Intense eau de Parfum',
    price: 142000,
    strong: 4,
    top: 4,
    second: 2,
    last: 5,
    des: '오리지널 오드퍼퓸에 블랙베리, 매혹적인 재스민 그리고 따스한 벤조인이 어우러져 더욱 강렬하면서도 짙은 프루티 향을 선사합니다.',
    image: `${root}bb_HerIntense.png`,
    gender: 1,
  },
  {
    index: 55,
    brand: '버버리',
    title: '윈저 토닉 오드 퍼퓸 (100ml)',
    etitle: 'Burberry Signature-Windsor Tonic',
    price: 320000,
    strong: 4,
    top: 2,
    second: 6,
    last: 1,
    des: '네롤리와 그린 만다린의 활기 가득한 노트가 시더우드, 카다멈, 머스크의 향기와 균형을 이룹니다. 자연에서 추출된 최고급 성분이 산뜻한 오드퍼퓸을 완성하며 독특한 상쾌함과 스파이시 우드의 향기가 조화를 이룹니다.',
    image: `${root}bb_Windsor.png`,
    gender: 3,
  },
  {
    index: 56,
    brand: '버버리',
    title: '하이 티 오드 퍼퓸 (100ml)',
    etitle: 'Burberry Signature-High Tea',
    price: 320000,
    strong: 4,
    top: 3,
    second: 2,
    last: 4,
    des: '영국의 라벤더 들판이 주는 싱그러운 생명력을 배경으로 웅장한 저택들 사이로 스며드는 햇빛 찬란한 순간을 표현했습니다. 로마 카모마일 추출물과 베르가못 에센스, 마테 속잎이 찻잎의 향기를 은은히 발하며, 라벤더의 파워풀한 플로럴 노트가 풍성함을 더하고 섬세한 네롤리가 향을 완성합니다.',
    image: `${root}bb_High.png`,
    gender: 3,
  },
  {
    index: 57,
    brand: '버버리',
    title: '미드나이트 저니 오드퍼퓸 (100ml)',
    etitle: 'Burberry Signature-Mid Night Journey',
    price: 320000,
    strong: 4,
    top: 3,
    second: 2,
    last: 1,
    des: '마법처럼 신비스러운 거리를 지나 꿈같이 머나먼 목적지로 향하는 여행을 떠오르게 하는 감각적인 향이 마음을 사로잡습니다. 블랙 앰버와 아로마틱한 블랙 페퍼가 향기로운 타임과 미르를 만나 이루는 매혹적이고 대담한 향의 오드퍼퓸. 장미와 라벤더 속잎의 부드러움과 생강의 생기가 절묘한 조화를 이룹니다. 자연에서 추출된 최고의 성분이 오리엔탈 꽃 향기를 선사하여 스파이스 아로마로 가득한 분주한 향신료 마켓을 떠올리게 합니다.',
    image: `${root}bb_MidNight.png`,
    gender: 3,
  },
  {
    index: 58,
    brand: '버버리',
    title: '튜더 로즈 오드퍼퓸 (100ml)',
    etitle: 'Burberry Signature-Tudor Rose',
    price: 320000,
    strong: 4,
    top: 3,
    second: 2,
    last: 5,
    des: '영국 켄징턴 정원의 장미 덤불이 연상되는 향으로 영국 역사를 수놓는 듯한 와일드한 아름다움을 보여줍니다.',
    image: `${root}bb_Tudor.png`,
    gender: 3,
  },
  {
    index: 59,
    brand: '버버리',
    title: '마이 버버리 오드 퍼퓸 ',
    etitle: 'My Burberry ',
    price: 134000,
    strong: 4,
    top: 2,
    second: 2,
    last: 5,
    des: '트렌치코트와 영국적 디자인, 장인정신의 헤리티지에서 영감을 받은 마이 버버리는 비에 촉촉이 젖은 런던 정원의 싱그러움을 담고 있습니다.',
    image: `${root}bb_My.png`,
    gender: 1,
  },
  {
    index: 60,
    brand: '버버리',
    title: '버버리 브릿',
    etitle: 'Burberry Brit for Her',
    price: 135000,
    strong: 3,
    top: 2,
    second: 2,
    last: 5,
    des: '트렌치코트와 영국적 디자인, 장인정신의 헤리티지에서 영감을 받은 마이 버버리는 비에 촉촉이 젖은 런던 정원의 싱그러움을 담고 있습니다.',
    image: `${root}bb_Brit.png`,
    gender: 1,
  },
  {
    index: 61,
    brand: '버버리',
    title: '버버리 히어로 오드 트왈렛',
    etitle: 'Burberry Hero',
    price: 95000,
    strong: 3,
    top: 2,
    second: 4,
    last: 2,
    des: '긍정의 힘을 지닌 영웅적 리더를 그려낸 캠페인은 남성과 말의 유사한 움직임을 통해 신체적 한계를 뛰어넘어 신화 속 존재로 변모하는 모습을 보여주며 새로운 남성, 히어로로서 재 탄생하는 자기 혁신을 은유적으로 그려냅니다.',
    image: `${root}bb_Hero.png`,
    gender: 2,
  },
  {
    index: 62,
    brand: '버버리',
    title: '미스터 버버리 인디고 오드트왈렛',
    etitle: 'Mr.Burberry Indigo',
    price: 90000,
    strong: 3,
    top: 3,
    second: 2,
    last: 2,
    des: '도시를 벗어나 즉흥적인 일상에서의 탈출을 통해 생기와 활력을 되찾는 대조적인 매력의 남성을 위한 미스터 버버리 인디고를 만나보세요. 레몬 오일, 블랙커런트 및 로즈마리가 어우러진 상큼한 허브향의 톱 노트, 제비꽃잎, 드리프트우드 및 그린 민트의 미들 노트 그리고 앰버, 화이트 오크 모스 및 머스크의 따뜻함과 흙내음이 느껴지는 베이스 노트로 구성되었습니다.',
    image: `${root}bb_Indigo.png`,
    gender: 2,
  },
  {
    index: 63,
    brand: '버버리',
    title: '미스터 버버리 인디고 오드트왈렛',
    etitle: 'Mr.Burberry Indigo',
    price: 90000,
    strong: 3,
    top: 3,
    second: 2,
    last: 2,
    des: '도시를 벗어나 즉흥적인 일상에서의 탈출을 통해 생기와 활력을 되찾는 대조적인 매력의 남성을 위한 미스터 버버리 인디고를 만나보세요. 레몬 오일, 블랙커런트 및 로즈마리가 어우러진 상큼한 허브향의 톱 노트, 제비꽃잎, 드리프트우드 및 그린 민트의 미들 노트 그리고 앰버, 화이트 오크 모스 및 머스크의 따뜻함과 흙내음이 느껴지는 베이스 노트로 구성되었습니다.',
    image: `${root}bb_Indigo.png`,
    gender: 2,
  },
  {
    index: 63,
    brand: '버버리',
    title: '앰버 히스 오드 퍼퓸 (100ml)',
    etitle: 'Burberry Signature-Amber Heath',
    price: 320000,
    strong: 4,
    top: 4,
    second: 5,
    last: 5,
    des: '고즈넉한 들판 가운데 펼쳐진 꽃으로 만개한 전원 풍경을 닮은 로맨틱한 향. 황금빛으로 노을 지는 저녁녘의 기대감. 앰버그리스 어코드 탑 노트와 파출리 미들 노트가 어우러진 모던한 앰버 향. 통카, 베티버, 바닐라의 잔향으로 마무리됩니다.',
    image: `${root}bb_Amber.png`,
    gender: 3,
  },
  {
    index: 64,
    brand: '버버리',
    title: '버버리 런던 오드트왈렛',
    etitle: 'Burberry London for men',
    price: 110000,
    strong: 3,
    top: 2,
    second: 5,
    last: 4,
    des: '짜릿하고 우디한 톱 노트와 미모사, 레더, 포트 와인의 섬세한 미들 노트 그리고 타바코 잎, 오포포낙스가 어우러진 베이스 노트로 구성되어있습니다.',
    image: `${root}bb_LondonMen.png`,
    gender: 2,
  },
  {
    index: 65,
    brand: '버버리',
    title: '버버리 브릿 스플래시 오드 트왈렛',
    etitle: 'Burberry Brit Splash',
    price: 110000,
    strong: 3,
    top: 3,
    second: 4,
    last: 5,
    des: '산뜻한 로즈마리로 밝고 상쾌하며 워터리 어코드의 미들노트로 시원한 아쿠아 계열 향수 입니다.',
    image: `${root}bb_BritSplash.png`,
    gender: 2,
  },
  {
    index: 66,
    brand: '바이레도',
    title: '데 로스 산토스',
    etitle: 'De Los Santos',
    price: 186000,
    strong: 4,
    top: 4,
    second: 2,
    last: 3,
    des: '삶을 기념하기 위해 탄생한 향수인 De Los Santos는 추억을 떠올리게 합니다.',
    image: `${root}br_Santos.png`,
    gender: 3,
  },
  {
    index: 67,
    brand: '바이레도',
    title: '발 다 프리크',
    etitle: 'Bal d`Afrique',
    price: 186000,
    strong: 4,
    top: 2,
    second: 3,
    last: 2,
    des: '아름다움과 환상에 중점을 둔 Bal d`Afrique는 Ben Gorham의 아프리카에게 보내는 러브 레터입니다. 아프리카의 춤, 예술 및 음악을 형성한 방식에 영감을 받아서 향을 제작하였습니다.',
    image: `${root}br_Afrique.png`,
    gender: 3,
  },
  {
    index: 68,
    brand: '바이레도',
    title: '집시 워터',
    etitle: 'Gypsy Water',
    price: 186000,
    strong: 4,
    top: 2,
    second: 2,
    last: 2,
    des: 'Gypsy Water는 로마 문화의 아름다움, 독특한 관습, 친밀한 신념 및 독특한 생활 방식에서 부터 영감을 받았습니다. 유목민의 다채로운 라이프스타일의 강렬한 앰버와 신선한 시트러스와 관련된 솔잎과 백단향의 우디 노트는 숲에서 보낸 집시의 밤의 열기를 불러일으킵니다.',
    image: `${root}br_Gypsy.png`,
    gender: 3,
  },
  {
    index: 69,
    brand: '바이레도',
    title: '모하비 고스트',
    etitle: 'Mojave Ghost',
    price: 186000,
    strong: 4,
    top: 4,
    second: 2,
    last: 2,
    des: '모하비 사막의 영혼이 담긴 아름다움에서 영감을 받은 우디계열의 향수 입니다. 가볍고 우아한 캐릭터와 함께 머스키한 Ambrette의 탑 노트와 신선한 자메이카 네스베리가 결합됩니다. 파우더리 바이올렛이 펼쳐져 샌달우드가 드러납니다. 마지막으로 따뜻한 샹티이 머스크가 산뜻한 앰버와 시더 우드 베이스를 마무리하고 모하비 고스트의 순수한 정신이 피부에 남아있게 합니다.',
    image: `${root}br_Mojave.png`,
    gender: 3,
  },
  {
    index: 70,
    brand: '바이레도',
    title: '셀리에',
    etitle: 'Sellier',
    price: 327000,
    strong: 5,
    top: 5,
    second: 3,
    last: 4,
    des: 'Sellier는 독특한 가죽향을 진하게 느끼게 해줄거에요. 첫 순간부터 놀라움을 느끼게 될겁니다. Sellier는 귀중한 담배 잎, 골동품 책, 오래된 가죽 클럽 의자가 있는 빈티지 흡연실로 우리를 보내 줄거에요.',
    image: `${root}br_Sellier.png`,
    gender: 3,
  },
  {
    index: 71,
    brand: '바이레도',
    title: '카사블랑카 릴리',
    etitle: 'Casablanca Lily',
    price: 325000,
    strong: 5,
    top: 4,
    second: 2,
    last: 3,
    des: '카사블랑카 릴리는 대서양 기슭에 떠 있는 번성하는 도시에서 영감을 받았습니다. 베르베르의 뿌리에서 식민지 유산에 이르기까지 카사블랑카의 현대적 정체성은 다양한 문화가 혼합되어 있으며 전통과 현대성이 끊임없이 변화하는 곳입니다. 시간이 지나면 도시는 스스로를 풀고 가장 놀라운 구석, 다른 곳에서는 볼 수 없는 모로코 생활의 생생한 만화경을 드러냅니다. 향기는 영감을 준 도시의 우아함처럼 당신을 감쌉니다. 풍요로움, 풍부함, 웅장함이 결합되어 있습니다.',
    image: `${root}br_Casablanca.png`,
    gender: 3,
  },
  {
    index: 72,
    brand: '바이레도',
    title: '타바코 만다린',
    etitle: 'Tobacco Mandarin',
    price: 325000,
    strong: 5,
    top: 2,
    second: 6,
    last: 5,
    des: '귤류와 향신료의 반짝이는 물결은 만다린, 코리앤더, 커민의 탑 노트를 통해 즉시 전달됩니다. 전통적이고 우아한 크리미한 가죽과 랍다넘이 향기를 고정하고 스모키한 마약의 망토 담배는 모든 것을 감쌉니다. 베이스에는 신성하고 세속적인 고대 수지와 숲이 있습니다. Olibanum 또는 Frankincense는 거룩하고 향기로운 단맛을, Oud와 Sandalwood는 뉘앙스로 매혹적인 부드러운 우디를 내포합니다.',
    image: `${root}br_TobaccoM.png`,
    gender: 3,
  },
  {
    index: 73,
    brand: '바이레도',
    title: '슬로우 댄스',
    etitle: 'Slow Dance',
    price: 186000,
    strong: 4,
    top: 4,
    second: 5,
    last: 5,
    des: '탑 노트에서는 앰버의 특성을 강하게 띄고 있어 향을 맡았을 때 달콤하면서 스모키한 느낌입니다. 미들노트에서는 부드러운 라다넘고무와 제비꽃 향이 섞여 오묘한 향기가 지속됩니다. 슬로우 댄스의 이름 그대로 마지막 잔향에서 극한의 매력을 발산합니다. 첫향보다 잔향이 더 매력적인 향수 입니다.',
    image: `${root}br_Slow.png`,
    gender: 3,
  },
  {
    index: 74,
    brand: '바이레도',
    title: '비블리오떼끄',
    etitle: 'Bibliothèque',
    price: 186000,
    strong: 4,
    top: 4,
    second: 2,
    last: 4,
    des: '오래된 도서관에서 나는 기분 좋은 향입니다. 시간이 정지된 세계에서 오래된 책 냄새 짙은 나무 선반에 배열된 가죽으로 된 페이지의 향기가 코를 자극합니다..',
    image: `${root}br_Bibliothèque.png`,
    gender: 3,
  },
  {
    index: 75,
    brand: '바이레도',
    title: '라 튤립',
    etitle: 'La Tulipe',
    price: 186000,
    strong: 4,
    top: 4,
    second: 2,
    last: 2,
    des: '튤립이 피기 시작하면 봄이 왔음을 알리는 신호입니다. 겨울의 지루한 날이 끝나면 정원은 대담한 색상과 깔끔한 ​​모양으로 활기를 띠게 됩니다. 튤립은 향기로운 꽃이라고 생각할 수 있는 첫 번째 꽃이 아닐 수도 있지만 많은 꽃은 확실히 달콤한 냄새가 납니다.',
    image: `${root}br_Tulipe.png`,
    gender: 3,
  },
  {
    index: 76,
    brand: '아쿠아디파르마',
    title: '콜로니아 퓨라 오 드 코롱',
    etitle: 'ColoNia Pura',
    price: 150000,
    strong: 2,
    top: 2,
    second: 1,
    last: 3,
    des: '아쿠아 디 파르마가 만든 콜로니아 퓨라의 꽃향기를 즐겨보세요. 싱싱하고 맑은 베르가못과 풍부한 오렌지 노트, 섬세한 페티그레인 향이 결합된 콜로니아 퓨라는 콜로니아의 고전적인 감귤향에 새로운 느낌을 받을 수 있습니다. 신선한 에너지와 현대적인 가벼운 향이 결합된 관능적인 남성성을 느껴보세요.',
    image: `${root}ap_Pura.png`,
    gender: 2,
  },
  {
    index: 77,
    brand: '아쿠아디파르마',
    title: '콜로니아 인텐자 오 드 코롱',
    etitle: 'ColoNia Intensa',
    price: 138000,
    strong: 2,
    top: 5,
    second: 4,
    last: 2,
    des: '콜로니아 인텐자는 베르가못과 레몬 노트의 기본 베이스에 우드와 레더 어코드가 추가되어 현대적이며 특별한 향을 즐길 수 있습니다. 카리스마있는 남성을 위해 디자인된 콜로니아 인텐자의 우아한 향기는 강하고 자신감있는 분위기를 만들어 줍니다.',
    image: `${root}ap_Intensa.png`,
    gender: 3,
  },
  {
    index: 78,
    brand: '아쿠아디파르마',
    title: '콜로니아 에센자 오 드 코롱',
    etitle: 'ColoNia Essenza',
    price: 150000,
    strong: 2,
    top: 2,
    second: 2,
    last: 3,
    des: '콜로니아 에센자는 강한 개성을 지닌 감귤향이 함유된 우디향입니다. 자몽, 만다린 및 페티그레인 노트와 같은 꽃 향기가 생생한 우디 패출리 베이스와 결합되어 더욱 생동감 있는 향기가 특징입니다. 세련된 우디 노트는 이 향수에 우아하고 차분한 느낌을 더해줍니다.',
    image: `${root}ap_Essenza.png`,
    gender: 3,
  },
  {
    index: 79,
    brand: '아쿠아디파르마',
    title: '미르토 디 파나레아(75ml)',
    etitle: 'Mirto di Panarea',
    price: 160000,
    strong: 3,
    top: 2,
    second: 5,
    last: 2,
    des: '아쿠아 디 파르마의 미르토 디 파나레아는 레몬과 베르가못 향기의 밝고 상큼한 과일 향이 특징입니다. 이 오드 뜨왈렛의 중심에는 마린브리즈 향과 자스민, 로즈의 향이 자리잡고 있으며 베이스노트에는 주니퍼, 시더 우드 및 앰버 노트의 조화로운 향을 느낄 수 있습니다.',
    image: `${root}ap_Mirto.png`,
    gender: 3,
  },
  {
    index: 80,
    brand: '아쿠아디파르마',
    title: '피코 디 아말피(75ml)',
    etitle: 'Fico di Amalfi',
    price: 160000,
    strong: 3,
    top: 2,
    second: 2,
    last: 2,
    des: '아쿠아 디 파르마가 만든 피코 디 아말피는 활력이 넘치는 향수입니다. 아말피 해안의 장엄한 전망을 느낄 수 있는 피코 디 아말피는 뛰어난 지속력과 활력을 불어넣는 향기를 선사합니다. 이 오드 뜨왈렛은 베르가못, 레몬, 자몽 및 시더우드의 과일향이 특징입니다. 무화과향과 핑크페퍼, 자스민 꽃잎향이 조화를 이루며 베이스노트로는 무화과나무, 시더우드 및 벤조인의 조화로운 향으로 마무리 됩니다.',
    image: `${root}ap_Fico.png`,
    gender: 3,
  },
  {
    index: 81,
    brand: '아쿠아디파르마',
    title: '우드(100ml)',
    etitle: 'OUD',
    price: 330000,
    strong: 4,
    top: 2,
    second: 3,
    last: 3,
    des: '침향나무의 진귀한 우드에센스가 따뜻하고 깊은 향을 내며 소중하고 강렬한 향기를 선사합니다. 베르가못과 오렌지로 이탈리안 클래식을, 아미리스로 동양적 고전미를 재현하고 머스크, 패출리, 침향나무가 조화된 우디함이 세련된 남성미를 부각시킵니다.',
    image: `${root}ap_OUD.png`,
    gender: 3,
  },
  {
    index: 82,
    brand: '아쿠아디파르마',
    title: '레더(100ml)',
    etitle: 'Leather',
    price: 330000,
    strong: 4,
    top: 2,
    second: 2,
    last: 4,
    des: '강렬한 카리스마를 가진 레더 오드 퍼퓸은 가죽을 만드는 전통에서 영감을 얻었습니다. 우아하고 독창적인 레더 어코드와 오렌지, 시칠리아 라임, 로즈 및 페티그레인 노트가 잊을 수 없는 깊은 향기로움을 선사합니다.',
    image: `${root}ap_Leather.png`,
    gender: 3,
  },
  {
    index: 83,
    brand: '아쿠아디파르마',
    title: '앰브라(100ml)',
    etitle: 'Ambra',
    price: 330000,
    strong: 4,
    top: 2,
    second: 6,
    last: 3,
    des: '앰브라는 앰버그리스의 진귀하고 관능적인 향을 가득 담았습니다. 강렬하고 우아한 향기의 앰버그리스 에센스와 베르가못, 로즈, 패출리, 샌달우드 등의 노트가 어우러져있습니다. 바다와 바람의 자연력을 통해 발전하는데 수년이 걸리는 희귀한 고대의 앰버그리스에서 관능적인 매력을 이끌어내는 예술적인 조합입니다.',
    image: `${root}ap_Ambra.png`,
    gender: 3,
  },
  {
    index: 84,
    brand: '아쿠아디파르마',
    title: '로사 노빌레',
    etitle: 'Rosa Nobile',
    price: 205000,
    strong: 4,
    top: 2,
    second: 2,
    last: 2,
    des: '귀중한 캐비지 로즈 새싹으로 만들어진 로사 노빌레의 향기는 시칠리아 만다린, 칼라브리안 베르가못 및 페퍼의 부드럽고 생생한 향으로 시작합니다. 이 오드 퍼퓸의 중심에는 모란, 제비꽃, 백합의 강렬하고 벨벳 같은 향과 이탈리아 장미의 풍성함과 조화를 이루고 베이스는 시더우드, 앰버그리스 및 머스크으로 이루어져있습니다.',
    image: `${root}ap_Rosa.png`,
    gender: 1,
  },
  {
    index: 85,
    brand: '아쿠아디파르마',
    title: '피오니아 노빌레',
    etitle: 'Peonia Nobile',
    price: 205000,
    strong: 4,
    top: 3,
    second: 2,
    last: 3,
    des: '아쿠아 디 파르마의 오 드 퍼퓸 피오니아 노빌레의 향은 섬세하면서도 활력이 넘치는 작약꽃에서 영감을 받았습니다. 이 향기는 상쾌하고 미세한 과일향이 나는 블랙페퍼와 라즈베리로 시작하며 화려한 작약, 제라늄, 터키 장미, 신선한 프리지아와 함께 하며, 베이스는 앰버, 패출리, 머스크으로 둘러싸여 있습니다.',
    image: `${root}ap_Peonia.png`,
    gender: 1,
  },
  {
    index: 86,
    brand: '르라보',
    title: '떼 마차 26',
    etitle: 'THÉ MATCHA 26',
    price: 253000,
    strong: 4,
    top: 4,
    second: 1,
    last: 2,
    des: '말차 티 어코드는 부드러운 베티버와 질감이 살아있는 삼나무를 바탕으로 크리미한 무화과 향을 가미하고 매혹적인 비터 오렌지로 기분을 고양시킵니다. 떼 마차 26은 고향, 환영받는 고독, 친숙하고 소중한 모든 것을 상기시키는 향기로운 것입니다.  내향적이고 본질적인 THÉ MATCHA 26은 피부 향으로, 착용자와 매우 가까이 있는 운이 좋은 사람들만을 위한 것입니다. 고귀한 고요함을 지니고 있습니다.일본 문화에서 말차가 단순한 음료가 아닌 것처럼 THÉ MATCHA 26은 우리에게 향기 그 이상입니다. 성찰의 순간, 은혜와 영혼의 아름다움에 대한 조용한 내적 축하를 제공하는 자아의 순간입니다. 간단한 냄새는 우리를 외부의 윙윙거리는 소리에서 벗어나 "안으로" 다시 데려옵니다. ',
    image: `${root}ll_MATCHA.png`,
    gender: 3,
  },
  {
    index: 87,
    brand: '르라보',
    title: '상탈 33',
    etitle: 'SANTAL 33',
    price: 253000,
    strong: 4,
    top: 3,
    second: 3,
    last: 2,
    des: '상탈 33은 `상탈`을 소재로 만든 향수 중 굉장히 잘 만든 향수입니다. 짙은 고동색의 시더우드,샌들우드 그리고 푸릇한 색이 가득한 파피루스 나무들이 울창하게 심어져 있는 오스트레일리아의 숲속에 비가 내렸을 때, 자욱한 물안개가 가득한 울창한 숲속을 걷다보면 흙, 풀과 나무에서 나는 촉촉하고 깊은 느낌의 나무 향기가 납니다.',
    image: `${root}ll_SANTAL.png`,
    gender: 3,
  },
  {
    index: 88,
    brand: '르라보',
    title: '어나더 13',
    etitle: 'ANOTHER 13',
    price: 253000,
    strong: 4,
    top: 4,
    second: 6,
    last: 2,
    des: '살내음의 향수를 찾으신다면 르라보의 어나더 13을 사용해보세요. 첫 향기는 잘 익은 바나나 껍질을 벗긴 후, 하얀 속살을 조심스럽게 썰어 따듯하고 고소한 보이차와 함께 입안에 넣은 듯한 달콤 쌉싸름한 향기가 납니다. 아기 살결의 뽀송함이면서 고소한 나무를 통으로 우려 낸듯한 따뜻한 암브레트 향이 느껴집니다.',
    image: `${root}ll_ANOTHER.png`,
    gender: 3,
  },
  {
    index: 89,
    brand: '르라보',
    title: '떼 누아 29',
    etitle: 'THÉ NOIR 29',
    price: 253000,
    strong: 4,
    top: 2,
    second: 2,
    last: 1,
    des: '솔나무 향을 베르가못의 향과 무화과 잎의 쌉싸름한 달콤함을 시작으로 건초더미에서 날 법한 스모키함을 블렌딩하여 르라보 특유의 묵직한 시더우드 향으로 마무리 되는 독특한 향기가 납니다.',
    image: `${root}ll_NOIR.png`,
    gender: 3,
  },
  {
    index: 90,
    brand: '르라보',
    title: '로즈 31',
    etitle: 'ROSE 31',
    price: 253000,
    strong: 4,
    top: 3,
    second: 2,
    last: 2,
    des: '바짝 마른 나무와 장미잎이 어우러진 흔하지 않은 중성적인 장미향수 입니다. 장미의 마른 잎과 담백하게 그을린 나무, 베티버의 향기가 조화롭게 어우러져 있습니다.',
    image: `${root}ll_ROSE.png`,
    gender: 3,
  },
  {
    index: 91,
    brand: '르라보',
    title: '베이 19',
    etitle: 'BAIE 19',
    price: 253000,
    strong: 4,
    top: 3,
    second: 4,
    last: 5,
    des: '오랜 가뭄 끝에 내린 소나기로 촉촉하고 풍요롭게 반짝이는 나무, 잎, 열매, 그리고 상쾌한 공기가 어우러져 만들어내는 신비로운 향기를 담아냈습니다.',
    image: `${root}ll_BAIE.png`,
    gender: 3,
  },
  {
    index: 92,
    brand: '르라보',
    title: '리스 41',
    etitle: 'LYS 41',
    price: 253000,
    strong: 4,
    top: 4,
    second: 2,
    last: 2,
    des: '비가 내린 후 물이 주는 선명하고 흠뻑 젖는 느낌의 향을 선사합니다.',
    image: `${root}ll_LYS.png`,
    gender: 3,
  },
  {
    index: 93,
    brand: '르라보',
    title: '통카 25',
    etitle: 'TONKA 25',
    price: 253000,
    strong: 4,
    top: 5,
    second: 6,
    last: 5,
    des: '첫 향은 살짝 매운 냄새가 코 끝을 자극할거에요. 하지만 금새 바닐라향이 매운냄새를 부드럽게 감싸주고 오렌지향이 은은하게 납니다.',
    image: `${root}ll_TONKA.png`,
    gender: 3,
  },
  {
    index: 94,
    brand: '르라보',
    title: '네롤리 36',
    etitle: 'NEROLI 36',
    price: 253000,
    strong: 4,
    top: 2,
    second: 2,
    last: 5,
    des: '네롤리는 오렌지 블라썸 에센스의 다른 이름입니다. 네롤리는 매우 따뜻하고 관능적인 베이스와 함께 햇볕이 잘 드는 플로럴 향수입니다. 로즈, 사향, 만다린 오렌지, 재스민, 바닐라 등의 에센스가 어우러져 Neroli 36의 스파이시함, 편안함, 열정 및 따뜻함을 선사합니다. ',
    image: `${root}ll_NEROLI.png`,
    gender: 3,
  },
  {
    index: 95,
    brand: '르라보',
    title: '플레르 도 오란져 27',
    etitle: 'FLEUR D`ORANGER 27',
    price: 253000,
    strong: 4,
    top: 2,
    second: 2,
    last: 5,
    des: '천연 오렌지 블로썸 원료를 3년이 넘는 시간을 걸쳐서 완성하였습니다. 프레쉬 플로럴,레몬 향을 더해 오렌지 블로썸 본연의 우아함을 더욱 살렸습니다.',
    image: `${root}ll_FLEUR.png`,
    gender: 3,
  },
  {
    index: 96,
    brand: '르라보',
    title: '자스민 17',
    etitle: 'JASMIN 17',
    price: 253000,
    strong: 4,
    top: 3,
    second: 5,
    last: 2,
    des: '`현대적인 느낌의 독착정인 자스민 향` 자스민 17은 기존의 플로럴 계열의 자스민이 아니라, 더욱 모던하게 해석한 향수 입니다. 센슈얼하면서도 여성스런 플로럴 향에 머스크, 샌달우드, 바닐라를 더해 더욱 장업하고 풍부하게 다가옵니다.',
    image: `${root}ll_JASMIN.png`,
    gender: 1,
  },
  {
    index: 97,
    brand: '르라보',
    title: '베티버 46',
    etitle: 'VETIVER 46',
    price: 253000,
    strong: 4,
    top: 5,
    second: 3,
    last: 2,
    des: '아이티에서 자란 최상급의 베티버를 원료로 해 만들어진 베티버 46은, 르 라보의 향수 컬렉션 중 가장 남성적인 매력의 향수입니다. 함께 블렌딩된 46가지의 원료들에는 남성적인 향이 가득합니다 : 페퍼, 가이악, 라다넘, 시더우드 각각이 강렬한 캐릭터를 드러냅니다. 여기에 신비로운 유향이 더해져 흥미롭고 유혹적인 잔향을 남깁니다.',
    image: `${root}ll_VETIVER.png`,
    gender: 2,
  },
  {
    index: 97,
    brand: '르라보',
    title: '패츌리 24',
    etitle: 'PATCHOULI 24',
    price: 253000,
    strong: 4,
    top: 5,
    second: 3,
    last: 1,
    des: '패출리 24는 보기 드문 매캐한 연기와 같은 강렬한 향입니다. 오히려 ‘나무 탄 내’에 가깝다. 흡사 연기에 검게 그을린 나무의 깊은 숯 향이 떠오른다. 이끼가 무성하고 이슬을 머금은 촉촉한 토양 대신에, 재가 흩뿌려진 토양이 떠오른다. 그만큼 패출리 24의 색채는 검다. 가장 높은 비중을 차지하고 있는 향조는 때죽나무라고도 하는 스타이랙스와 자작나무. 스모키한 우디 노트와 패출리의 절묘한 절충점이다. 연기에 그을린 나무의 향기가 아주 특별하면서도 미쳐 날뛰지 않고 부드러우며, 더할 나위 없이 질서정연합니다.',
    image: `${root}ll_PATCHOULI.png`,
    gender: 2,
  },
  {
    index: 98,
    brand: '르라보',
    title: '일랑 49',
    etitle: 'YLANG 49',
    price: 253000,
    strong: 4,
    top: 4,
    second: 4,
    last: 3,
    des: '일랑일랑과 타히티 가드니아가 어우려져 관능적인 시프레 플로럴 향수를 나타냅니다. 패출리, 오크모스,베티버, 샌달우드와 벤조인이 더욱 향을 센슈얼하게 만듭니다.',
    image: `${root}ll_YLANG.png`,
    gender: 1,
  },
  {
    index: 99,
    brand: '르라보',
    title: '암브레트 9',
    etitle: 'AMBRETTE 9',
    price: 253000,
    strong: 4,
    top: 4,
    second: 1,
    last: 3,
    des: '사과, 배 같은 가을 과일에서 느껴지는 상큼함과 달달함을 가진 과일향을 시작으로 부드러운 살 냄새가 퍼져나옵니다.',
    image: `${root}ll_AMBRETTE.png`,
    gender: 1,
  },
  {
    index: 100,
    brand: '르라보',
    title: '아이리스 39',
    etitle: 'IRIS 39',
    price: 253000,
    strong: 4,
    top: 4,
    second: 2,
    last: 2,
    des: '비가 내린 뒤 숲 속의 나무와 흙내음을 연상시키는 우아한 플로럴 우디향입니다. 최상급 향수 원료인 아이리스와 패츌리의 센슈얼함을 더해 우아한 우디향을 전해줍니다.',
    image: `${root}ll_IRIS.png`,
    gender: 1,
  },
];
